// Auto-generated by scripts/generate-native-versions.mjs. Do not edit manually.
// Source of truth: native/dart/packages/blocks_runtime/pubspec.yaml

/// Semver of this AWS Blocks Dart runtime library.
const String blocksRuntimeVersion = '0.1.3';

/// The user agent token for this runtime, e.g. `aws-blocks-dart/0.1.3`.
/// Keep the `aws-blocks` prefix: rows without it do not appear in reporting.
const String blocksUserAgentToken = 'aws-blocks-dart/$blocksRuntimeVersion';
