// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, it } from 'node:test';
import { syncSchema } from './schema-sync.js';

let dir: string;
let migrations: string;
let out: string;

function migration(name: string, sql: string): void {
	writeFileSync(join(migrations, name), sql);
}

beforeEach(() => {
	dir = mkdtempSync(join(tmpdir(), 'schema-sync-test-'));
	migrations = join(dir, 'migrations');
	out = join(dir, 'generated');
	mkdirSync(migrations, { recursive: true });
});

afterEach(() => {
	rmSync(dir, { recursive: true, force: true });
});

describe('syncSchema', () => {
	it('derives row types from a migration', async () => {
		migration(
			'001_notes.sql',
			'CREATE TABLE notes (id SERIAL PRIMARY KEY, text TEXT NOT NULL, done BOOLEAN NOT NULL DEFAULT FALSE);',
		);

		const result = await syncSchema({ migrationsPath: migrations, outDir: out });
		assert.deepEqual(result.tables, ['notes']);

		const types = readFileSync(join(out, 'database.types.ts'), 'utf-8');
		assert.match(types, /export interface Notes \{/);
		assert.match(types, /id: number;/);
		assert.match(types, /text: string;/);
		assert.match(types, /done: boolean;/);
	});

	it('types temporal columns as Date, matching what the driver returns', async () => {
		// The shared `db pull` mapping calls these `string`, but pg and PGlite both
		// hydrate them into Date instances. A generated type that lies defeats the
		// purpose, so schema sync corrects it.
		migration(
			'001_times.sql',
			`CREATE TABLE events (
				id SERIAL PRIMARY KEY,
				at TIMESTAMPTZ NOT NULL,
				naive TIMESTAMP NOT NULL,
				day DATE NOT NULL,
				clock TIME NOT NULL
			);`,
		);

		await syncSchema({ migrationsPath: migrations, outDir: out });
		const types = readFileSync(join(out, 'database.types.ts'), 'utf-8');

		assert.match(types, /at: Date;/);
		assert.match(types, /naive: Date;/);
		assert.match(types, /day: Date;/);
		// Time-of-day has no date part; the drivers return it as a string.
		assert.match(types, /clock: string;/);
	});

	it('marks a nullable column as nullable', async () => {
		migration('001_notes.sql', 'CREATE TABLE notes (id SERIAL PRIMARY KEY, note TEXT);');

		await syncSchema({ migrationsPath: migrations, outDir: out });
		assert.match(readFileSync(join(out, 'database.types.ts'), 'utf-8'), /note: string \| null;/);
	});

	it('emits runtime metadata with the primary key and auto-generated columns', async () => {
		migration(
			'001_notes.sql',
			`CREATE TABLE notes (
				id SERIAL PRIMARY KEY,
				text TEXT NOT NULL,
				created_at TIMESTAMPTZ NOT NULL DEFAULT now()
			);`,
		);

		await syncSchema({ migrationsPath: migrations, outDir: out });
		const meta = readFileSync(join(out, 'database.meta.ts'), 'utf-8');

		assert.match(meta, /primaryKey: 'id'/);
		// SERIAL and DEFAULT now() are server-managed, so they're excluded from insert input.
		assert.match(meta, /autoGenerated: \['id', 'created_at'\]/);
		assert.match(meta, /columns: \['id', 'text', 'created_at'\]/);
	});

	it('picks up a new column when a migration is added', async () => {
		migration('001_notes.sql', 'CREATE TABLE notes (id SERIAL PRIMARY KEY, text TEXT NOT NULL);');
		await syncSchema({ migrationsPath: migrations, outDir: out });
		assert.doesNotMatch(readFileSync(join(out, 'database.types.ts'), 'utf-8'), /priority/);

		// This is the moment being sold: add a migration, types follow, no command.
		migration('002_priority.sql', 'ALTER TABLE notes ADD COLUMN priority INTEGER NOT NULL DEFAULT 0;');
		const result = await syncSchema({ migrationsPath: migrations, outDir: out });

		assert.match(readFileSync(join(out, 'database.types.ts'), 'utf-8'), /priority: number;/);
		assert.ok(result.written.length > 0, 'expected the changed files to be rewritten');
	});

	it('does not rewrite files when the schema is unchanged', async () => {
		migration('001_notes.sql', 'CREATE TABLE notes (id SERIAL PRIMARY KEY);');
		await syncSchema({ migrationsPath: migrations, outDir: out });
		const before = statSync(join(out, 'database.types.ts')).mtimeMs;

		const second = await syncSchema({ migrationsPath: migrations, outDir: out });

		// Rewriting unconditionally would retrigger a watching dev server forever.
		assert.deepEqual(second.written, []);
		assert.equal(statSync(join(out, 'database.types.ts')).mtimeMs, before);
	});

	it('handles multiple tables', async () => {
		migration(
			'001_two.sql',
			`CREATE TABLE authors (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
			 CREATE TABLE books (id SERIAL PRIMARY KEY, author_id INTEGER REFERENCES authors(id));`,
		);

		const result = await syncSchema({ migrationsPath: migrations, outDir: out });
		assert.deepEqual([...result.tables].sort(), ['authors', 'books']);

		const types = readFileSync(join(out, 'database.types.ts'), 'utf-8');
		assert.match(types, /export interface Authors \{/);
		assert.match(types, /export interface Books \{/);
	});

	it('surfaces a broken migration with the real Postgres error', async () => {
		migration('001_bad.sql', 'CREATE TABL notes (id SERIAL);');

		await assert.rejects(
			() => syncSchema({ migrationsPath: migrations, outDir: out }),
			(e) => {
				assert.match(String(e), /syntax error/i);
				return true;
			},
		);
	});

	it('preserves a hand-edited singular across regeneration', async () => {
		migration('001_data.sql', 'CREATE TABLE data (id SERIAL PRIMARY KEY);');
		await syncSchema({ migrationsPath: migrations, outDir: out });

		const metaPath = join(out, 'database.meta.ts');
		writeFileSync(metaPath, readFileSync(metaPath, 'utf-8').replace(/singular: '[^']*'/, "singular: 'datum'"));

		migration('002_more.sql', 'ALTER TABLE data ADD COLUMN label TEXT;');
		await syncSchema({ migrationsPath: migrations, outDir: out });

		assert.match(readFileSync(metaPath, 'utf-8'), /singular: 'datum'/);
	});
});
