// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Configuration options for the Database Building Block.
 */
import type { ChildLogger } from '@aws-blocks/bb-logger';
export interface DatabaseOptions {
  /** Minimum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  minCapacity?: number;
  /** Maximum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  maxCapacity?: number;
  /** Database name. Derived from scope.fullId if omitted. */
  databaseName?: string;
  /** Wrap an existing database instead of creating one. */
  connection?: ExternalDatabaseRef;
  /** Path to directory containing numbered `.sql` migration files. */
  migrationsPath?: string;
  /** Runtime schema metadata for crud(). Generated by `db pull`. */
  schema?: import('./crud/types.js').TableSchema;
  /**
   * RLS enforcement policy for this database. Set by `db pull` when introspection
   * detects tables with RLS enabled.
   *
   * **Important:** `'enforce'` currently applies ONLY to `db.crud()` operations
   * (which always route through `withRLS()`). Raw `db.query()` / `db.execute()` /
   * `db.transaction()` calls bypass RLS unless you explicitly use
   * `db.withRLS({ userId })`. If you hand-write queries, you must opt in yourself.
   */
  rlsPolicy?: 'enforce';
  /**
   * CloudFormation removal policy for the Aurora cluster. When omitted, the
   * stack-wide `defaults` apply (`production` → RETAIN so data is preserved on
   * `cdk destroy`; `sandbox` → DESTROY). Pass `'destroy'`/`'retain'`/`'snapshot'`
   * to override for this one database. Deletion protection follows: on unless
   * the cluster is being destroyed.
   */
  removalPolicy?: 'destroy' | 'retain' | 'snapshot';
  /**
   * Aurora PostgreSQL engine version, e.g. `'16.13'`.
   *
   * Configurable because AWS periodically retires older Aurora PostgreSQL minor
   * versions: 16.4 was retired in us-east-1, after which `CreateDBCluster` began
   * failing with `Cannot find version 16.4 for aurora-postgresql`. Surfacing this
   * as an option means the next retirement is a config change, not a framework fix.
   * @default '16.13'
   */
  postgresVersion?: string;
	/** Optional logger for internal operations. When omitted, a default Logger at error level is created. */
	logger?: ChildLogger;
  /**
   * Where to place the Aurora cluster when the app runs in a VPC. Optional; by
   * default Blocks prefers an **isolated** subnet tier (keeping the database off
   * any NAT path) and falls back to `private-with-egress` if the VPC has no
   * isolated tier. Aurora is reached over the RDS Data API (HTTPS via a VPC
   * endpoint), so placement affects isolation posture, not reachability.
   *
   * A CDK-free mirror of `ec2.SubnetSelection` — the `Database` constructor
   * resolves to a runtime entry point that must not import `aws-cdk-lib`, so
   * subnets are referenced by **id** (a plain string, as CDK identifies them)
   * and the tier by a string. The CDK layer resolves these against the VPC.
   */
  subnets?: SubnetSelection;
  /**
   * ARN of an existing customer-managed KMS key to use for the Aurora cluster's
   * storage-at-rest encryption. The same key also encrypts the cluster's
   * auto-generated credentials secret. When omitted, storage is still encrypted,
   * but with the account's AWS-managed `aws/rds` key — storage encryption is
   * always on regardless of this option.
   *
   * Referenced by **ARN** (a plain string) rather than a `kms.IKey` for the same
   * reason as `subnets`: the `Database` constructor resolves to a runtime entry
   * point that must not import `aws-cdk-lib`. The CDK layer rehydrates the ARN
   * into a `kms.IKey` (via `kms.Key.fromKeyArn`) and passes it to the cluster.
   *
   * **Requirements for the key you pass.** The key is *imported* — Blocks binds
   * to it by ARN and does not (cannot) modify its key policy — so the key's
   * policy must already permit the principals that use it:
   * - The **deploying principal** needs `kms:CreateGrant` and `kms:DescribeKey`
   *   on the key: RDS uses a grant to encrypt the cluster's storage volume with it.
   * - The runtime path reads the credentials secret over the RDS Data API, so
   *   the principal reading it needs `kms:Decrypt` on the key. `secret.grantRead`
   *   adds the identity-side permission; the key policy must still allow it.
   * - The key must be in the **same account and region** as the cluster.
   *
   * **Why this is a flat ARN** (rather than the `encryption:
   * 'aws-managed' | 'customer-managed' | fromKmsKey(arn)` shape used by
   * `bb-distributed-table` / `bb-kv-store`): `Database` resolves to a runtime
   * entry point that must not import `aws-cdk-lib`, so it cannot expose the
   * CDK-helper `fromKmsKey()` form, and the Data-API access model means there is
   * no per-table managed-key choice to model — storage is either AWS-managed
   * (default) or the one customer-managed key named here. Unifying the option
   * shape across the data blocks is tracked as a follow-up.
   */
  storageEncryptionKeyArn?: string;
  /**
   * Automated-backup retention for the Aurora cluster, which is also its
   * point-in-time-recovery (PITR) window — Aurora keeps continuous backups
   * within this window and restores from it.
   *
   * A single knob, since the recovery window only means anything when backups
   * are on:
   * - `true` — enable backups with the standard 15-day window.
   * - `false` — Aurora **cannot** turn automated backups off (the cluster
   *   minimum is 1 day), so this clamps to the 1-day minimum rather than
   *   disabling them.
   * - `{ retentionDays: n }` — enable backups and pin the window. Aurora
   *   requires an integer **1–35**; an out-of-range value warns at synth and
   *   falls back to the 15-day default.
   *
   * When omitted, the stack-wide default applies (`defaults.pointInTimeRecovery`
   * from `BlocksPresets` — on under `production`, off under `sandbox`; a `false`
   * default lands on the 1-day minimum per the clamp above). A per-block value
   * always wins. The CDK layer resolves this into the cluster's backup retention.
   */
  pointInTimeRecovery?: boolean | { retentionDays: number };
}

/**
 * A CDK-free structural mirror of the inputs of `ec2.SubnetSelection`, safe to
 * reference from the runtime-resolved `Database` constructor (no `aws-cdk-lib`
 * import). The CDK layer maps `subnetType` (string) to `ec2.SubnetType`,
 * rehydrates `subnetIds` via `Subnet.fromSubnetId`, and passes the AZ/group/
 * onePerAz fields through unchanged. Set at most one of `subnetType`,
 * `subnetGroupName`, or `subnetIds` (mirrors CDK's mutual exclusion).
 */
export interface SubnetSelection {
  /** Select all subnets of the given tier. Proxy for `ec2.SubnetType`. */
  subnetType?: 'isolated' | 'private-with-egress' | 'public';
  /** Restrict the selection to these Availability Zones (filter). */
  availabilityZones?: string[];
  /** Return at most one subnet per AZ. */
  onePerAz?: boolean;
  /** Select a named subnet group (from the VPC's `subnetConfiguration`). */
  subnetGroupName?: string;
  /** Explicitly select individual subnets by id. Mirrors `ec2` `subnets: ISubnet[]`. */
  subnetIds?: string[];
}

/**
 * Reference to an external database not managed by this Building Block.
 * Used with `Database.fromExisting()`.
 */
export type ExternalDatabaseRef =
  | { host: string; port?: number; database: string; secretArn: string }
  | {
      connectionString: string | { get(): Promise<string> };
      /**
       * TLS settings for the connection. When omitted, the server certificate is
       * **verified by default** (the engine uses `{ rejectUnauthorized: true }`).
       *
       * Managed Postgres providers (Supabase, Neon, RDS) present certificates
       * signed by a provider-specific CA that is not in Node's built-in trust
       * store, so verification requires pinning that CA via `ca`. For Supabase,
       * download `prod-ca-2021.crt` from Database Settings → SSL Configuration.
       *
       * Set `rejectUnauthorized: false` only if you accept the man-in-the-middle
       * risk (encrypted but unauthenticated); prefer pinning the CA instead.
       */
      ssl?: ExternalSslOptions;
    };

/**
 * TLS policy for an external database connection.
 *
 * Modeled as a discriminated union on `rejectUnauthorized` so that a misleading
 * combination is a **compile-time error**: a pinned `ca` is only meaningful when
 * the certificate is actually verified, and node `pg` silently ignores `ca` when
 * `rejectUnauthorized: false`. Expressing `{ ca, rejectUnauthorized: false }` —
 * which looks secure but is not — therefore won't type-check.
 *
 * - `{ rejectUnauthorized?: true; ca?: string }` — verify the server certificate
 *   (the default). Omit `ca` to verify against Node's built-in trust store
 *   (publicly-trusted certs); supply `ca` to pin a provider's private CA.
 * - `{ rejectUnauthorized: false }` — do NOT verify (encrypted but
 *   man-in-the-middle-exposed). A `ca` is not accepted here because it would be ignored.
 */
export type ExternalSslOptions =
  | { rejectUnauthorized?: true; ca?: string }
  | { rejectUnauthorized: false };
