// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Configuration options for the Database Building Block.
 */
import type { ChildLogger } from '@aws-blocks/bb-logger';
import type { SqlQuery } from '@aws-blocks/data-common';
export interface DatabaseOptions {
  /** Minimum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  minCapacity?: number;
  /** Maximum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  maxCapacity?: number;
  /** Database name. Derived from scope.fullId if omitted. */
  databaseName?: string;
  /** Wrap an existing database instead of creating one. */
  connection?: ExternalDatabaseRef;
  /** Path to directory containing numbered `.sql` migration files. */
  migrationsPath?: string;
  /** Runtime schema metadata for crud(). Generated by `db pull`. */
  schema?: import('./crud/types.js').TableSchema;
  /**
   * RLS enforcement policy for this database. Set by `db pull` when introspection
   * detects tables with RLS enabled.
   *
   * **Important:** `'enforce'` currently applies ONLY to `db.crud()` operations
   * (which always route through `withRLS()`). Raw `db.query()` / `db.execute()` /
   * `db.transaction()` calls bypass RLS unless you explicitly use
   * `db.withRLS({ userId })`. If you hand-write queries, you must opt in yourself.
   */
  rlsPolicy?: 'enforce';
  /**
   * CloudFormation removal policy for the Aurora cluster. When omitted, the
   * stack-wide `defaults` apply (`production` → RETAIN so data is preserved on
   * `cdk destroy`; `sandbox` → DESTROY). Pass `'destroy'`/`'retain'`/`'snapshot'`
   * to override for this one database. Deletion protection follows: on unless
   * the cluster is being destroyed.
   */
  removalPolicy?: 'destroy' | 'retain' | 'snapshot';
  /**
   * Aurora PostgreSQL engine version, e.g. `'16.13'`.
   *
   * Configurable because AWS periodically retires older Aurora PostgreSQL minor
   * versions: 16.4 was retired in us-east-1, after which `CreateDBCluster` began
   * failing with `Cannot find version 16.4 for aurora-postgresql`. Surfacing this
   * as an option means the next retirement is a config change, not a framework fix.
   * @default '16.13'
   */
  postgresVersion?: string;
	/** Optional logger for internal operations. When omitted, a default Logger at error level is created. */
	logger?: ChildLogger;
  /**
   * Where to place the Aurora cluster when the app runs in a VPC. Optional; by
   * default Blocks prefers an **isolated** subnet tier (keeping the database off
   * any NAT path) and falls back to `private-with-egress` if the VPC has no
   * isolated tier. Aurora is reached over the RDS Data API (HTTPS via a VPC
   * endpoint), so placement affects isolation posture, not reachability.
   *
   * A CDK-free mirror of `ec2.SubnetSelection` — the `Database` constructor
   * resolves to a runtime entry point that must not import `aws-cdk-lib`, so
   * subnets are referenced by **id** (a plain string, as CDK identifies them)
   * and the tier by a string. The CDK layer resolves these against the VPC.
   */
  subnets?: SubnetSelection;
  /**
   * Stream rows from these tables to clients with `db.shape()`. The client keeps
   * a local copy of each shape and gets live updates as rows change.
   *
   * On AWS this enables logical replication on the Aurora cluster and runs an
   * [Electric](https://electric.ax) sync service on Fargate. Locally it runs an
   * in-process emulator of the same HTTP protocol on top of PGlite.
   *
   * Constraints:
   * - Not supported with `connection` (`fromExisting()`) yet.
   * - Not supported with `minCapacity: 0`: Aurora does not auto-pause while
   *   logical replication is enabled, so scale-to-zero cannot take effect.
   * - Each table needs a single-column primary key.
   *
   * @example
   * const db = new Database(scope, 'main', {
   *   migrationsPath: './aws-blocks/migrations',
   *   sync: { tables: ['todos'] },
   * });
   */
  sync?: SyncOptions;
}

/**
 * Configuration for `Database({ sync })`.
 */
export interface SyncOptions {
  /**
   * Tables that `db.shape()` may stream. Only these tables are added to the
   * replication publication and readable by the sync service. Use unquoted
   * Postgres identifiers, optionally schema-qualified (`'todos'`, `'app.todos'`).
   */
  tables: string[];
  /** Sizing and version of the Electric sync service (AWS only). */
  electric?: ElectricServiceOptions;
}

/**
 * Sizing and version of the Electric sync service that `sync` runs on AWS.
 */
export interface ElectricServiceOptions {
  /**
   * Electric release to run. The stack builds this release from Electric's
   * source tag in your account (CodeBuild → a stack-owned ECR repository) on
   * the first deploy and whenever the version changes; the first build takes
   * about 15 minutes. Ignored when `image` is set.
   * @default '1.8.1'
   */
  version?: string;
  /**
   * A prebuilt Electric image (linux/amd64) to run instead of building one,
   * for example from your own registry. When set, no build runs.
   */
  image?: string;
  /** Fargate vCPU units. @default 512 */
  cpu?: number;
  /** Fargate memory in MiB. @default 1024 */
  memoryMiB?: number;
}

/**
 * Options for `db.shape()`. A shape is a table, an optional row filter, and an
 * optional column list. The server fixes all three when it issues the shape;
 * the client cannot change them.
 */
export interface ShapeOptions<T> {
  /** The table to stream. Must be listed in `sync.tables`. */
  table: string;
  /**
   * Row filter, written with the `sql` tag. Values become bound parameters, so
   * user input is never concatenated into the filter.
   *
   * @example sql`owner_id = ${user.userId} AND done = ${false}`
   */
  where?: SqlQuery;
  /** Columns to stream. Must include `key`. Defaults to all columns. */
  columns?: (keyof T & string)[];
  /**
   * The table's primary-key column. `Shape.get()` looks rows up by this column.
   * @default 'id'
   */
  key?: keyof T & string;
  /**
   * How long the client may use this shape before it must ask the server for a
   * new one. The client refreshes automatically by calling the same API method
   * again, which re-runs your authorization check.
   * @default 3600
   */
  ttlSeconds?: number;
}

/**
 * Wire form of a {@link Shape}. Produced by `Shape.toJSON()` when an API
 * method returns a shape, and hydrated back into a live `Shape` on the client.
 */
export interface ShapeDescriptor {
  __blocks: 'data/shape';
  /** Path of the shape endpoint, relative to the backend origin. */
  path: string;
  /** Signed, expiring token that fixes the table, filter, and columns. */
  token: string;
  /** Primary-key column name. */
  key: string;
  /** Token expiry, in epoch milliseconds. */
  expiresAt: number;
}

/**
 * A live, local copy of the rows that match a shape.
 *
 * Return a shape from an `ApiNamespace` method; the client receives a hydrated
 * `Shape` that syncs in the background. Reads (`rows`, `get()`) are local and
 * synchronous: they never wait on the network.
 *
 * Row values arrive in their Postgres text form and are parsed for common
 * types: `int2`/`int4`/`float4`/`float8` → `number`, `int8` → `bigint`,
 * `bool` → `boolean`, `json`/`jsonb` → parsed JSON. Other types (`numeric`,
 * `timestamptz`, `uuid`, …) arrive as `string`. Declare `T` to match.
 *
 * @example
 * // Backend
 * async todos() {
 *   const user = await auth.requireAuth(context);
 *   return db.shape<Todo>({ table: 'todos', where: sql`owner_id = ${user.userId}` });
 * }
 *
 * // Frontend
 * const todos = await api.todos();
 * await todos.ready;
 * todos.subscribe((rows) => render(rows));
 * const one = todos.get('todo-1'); // local lookup, no network
 */
export interface Shape<T> {
  /** Current rows. Replaced (not mutated) on every change. */
  readonly rows: readonly T[];
  /** Look up a row by primary key. Local and synchronous. */
  get(key: string | number | bigint): T | undefined;
  /** Resolves once the initial rows have arrived. Starts syncing if needed. */
  readonly ready: Promise<void>;
  /** `true` once the local copy has caught up with the server. */
  readonly isUpToDate: boolean;
  /**
   * Call `listener` after every change. Starts syncing if needed. Returns an
   * unsubscribe function. Compatible with React's `useSyncExternalStore`
   * together with {@link Shape.getSnapshot}.
   */
  subscribe(listener: (rows: readonly T[]) => void): () => void;
  /** The current `rows` array. Stable between changes. */
  getSnapshot(): readonly T[];
  /**
   * Resolve when a write made in transaction `txid` has synced into this
   * shape. Use the value from `currentTxid(tx)` returned by your write method.
   */
  waitForTxid(txid: string): Promise<void>;
  /** Stop syncing and release the connection. */
  close(): void;
  /** Transferable serialization. Called automatically by `JSON.stringify`. */
  toJSON(): ShapeDescriptor;
}

/**
 * A CDK-free structural mirror of the inputs of `ec2.SubnetSelection`, safe to
 * reference from the runtime-resolved `Database` constructor (no `aws-cdk-lib`
 * import). The CDK layer maps `subnetType` (string) to `ec2.SubnetType`,
 * rehydrates `subnetIds` via `Subnet.fromSubnetId`, and passes the AZ/group/
 * onePerAz fields through unchanged. Set at most one of `subnetType`,
 * `subnetGroupName`, or `subnetIds` (mirrors CDK's mutual exclusion).
 */
export interface SubnetSelection {
  /** Select all subnets of the given tier. Proxy for `ec2.SubnetType`. */
  subnetType?: 'isolated' | 'private-with-egress' | 'public';
  /** Restrict the selection to these Availability Zones (filter). */
  availabilityZones?: string[];
  /** Return at most one subnet per AZ. */
  onePerAz?: boolean;
  /** Select a named subnet group (from the VPC's `subnetConfiguration`). */
  subnetGroupName?: string;
  /** Explicitly select individual subnets by id. Mirrors `ec2` `subnets: ISubnet[]`. */
  subnetIds?: string[];
}

/**
 * Reference to an external database not managed by this Building Block.
 * Used with `Database.fromExisting()`.
 */
export type ExternalDatabaseRef =
  | { host: string; port?: number; database: string; secretArn: string }
  | {
      connectionString: string | { get(): Promise<string> };
      /**
       * TLS settings for the connection. When omitted, the server certificate is
       * **verified by default** (the engine uses `{ rejectUnauthorized: true }`).
       *
       * Managed Postgres providers (Supabase, Neon, RDS) present certificates
       * signed by a provider-specific CA that is not in Node's built-in trust
       * store, so verification requires pinning that CA via `ca`. For Supabase,
       * download `prod-ca-2021.crt` from Database Settings → SSL Configuration.
       *
       * Set `rejectUnauthorized: false` only if you accept the man-in-the-middle
       * risk (encrypted but unauthenticated); prefer pinning the CA instead.
       */
      ssl?: ExternalSslOptions;
    };

/**
 * TLS policy for an external database connection.
 *
 * Modeled as a discriminated union on `rejectUnauthorized` so that a misleading
 * combination is a **compile-time error**: a pinned `ca` is only meaningful when
 * the certificate is actually verified, and node `pg` silently ignores `ca` when
 * `rejectUnauthorized: false`. Expressing `{ ca, rejectUnauthorized: false }` —
 * which looks secure but is not — therefore won't type-check.
 *
 * - `{ rejectUnauthorized?: true; ca?: string }` — verify the server certificate
 *   (the default). Omit `ca` to verify against Node's built-in trust store
 *   (publicly-trusted certs); supply `ca` to pin a provider's private CA.
 * - `{ rejectUnauthorized: false }` — do NOT verify (encrypted but
 *   man-in-the-middle-exposed). A `ca` is not accepted here because it would be ignored.
 */
export type ExternalSslOptions =
  | { rejectUnauthorized?: true; ca?: string }
  | { rejectUnauthorized: false };
