// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Wire-level regression: a client-visible RPC error body must never carry the
 * database schema (table / column names) or raw driver text.
 *
 * These errors are thrown server-side with full diagnostic detail on purpose —
 * the identifier-allowlist rejection lists the valid columns, and a driver error
 * names the relation — so a developer reading logs can act on them. What matters
 * is that the RPC serializer never forwards that detail to an (often anonymous)
 * caller. Each case drives the REAL bb-data error through the REAL Lambda RPC
 * handler and inspects the response body the client receives.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { createLambdaHandler } from '@aws-blocks/core/lambda-handler';
import { isBlocksError } from '@aws-blocks/core';
import { buildSelect } from './sql-builder.js';
import type { TableMetaEntry } from './types.js';
import { translatePgError } from '../engines/pg-error-translator.js';
import { DatabaseErrors } from '../errors.js';

// A caller-shaped row type that names a column the table doesn't have — the
// request a malformed or probing client would send.
type ProbeRow = { id: string; not_a_column: string };

const meta: TableMetaEntry = {
  singular: 'customer',
  plural: 'customers_internal',
  primaryKey: 'id',
  columns: ['id', 'email', 'ssn_hash', 'stripe_customer_id', 'created_at'],
  autoGenerated: ['id', 'created_at'],
};

/** Invoke `api.<method>` over the Lambda RPC path and return the parsed response body. */
async function rpc(method: () => Promise<unknown>): Promise<{ raw: string; error?: { code: number; message: string; data?: { name?: string } } }> {
  const backend = { api: () => ({ run: method }) };
  const handler = createLambdaHandler(async () => backend);
  const originalError = console.error;
  const originalDebug = console.debug;
  console.error = () => {};
  console.debug = () => {};
  try {
    const res = (await handler({
      httpMethod: 'POST',
      path: '/aws-blocks/api',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ jsonrpc: '2.0', method: 'api.run', params: [], id: 1 }),
      isBase64Encoded: false,
    } as never)) as { body: string };
    return { raw: res.body, ...JSON.parse(res.body) };
  } finally {
    console.error = originalError;
    console.debug = originalDebug;
  }
}

function assertNoSchema(raw: string): void {
  for (const secret of ['customers_internal', 'ssn_hash', 'stripe_customer_id', 'email', 'valid:']) {
    assert.ok(!raw.includes(secret), `client-visible error body leaked "${secret}": ${raw}`);
  }
}

describe('client-visible RPC errors carry no schema or driver text', () => {
  it('an unknown-column rejection (which lists every valid column) reaches the client as a generic error', async () => {
    // Sanity: server-side, the rejection does carry the column list (useful in logs).
    assert.throws(
      () => buildSelect<ProbeRow>('customers_internal', { select: ['not_a_column'] }, meta),
      /valid: id, email, ssn_hash/,
    );

    const body = await rpc(async () => buildSelect<ProbeRow>('customers_internal', { select: ['not_a_column'] }, meta));
    assert.ok(body.error, 'the call must fail');
    assertNoSchema(body.raw);
    assert.ok(!body.raw.includes('not_a_column'), 'the rejected identifier must not be echoed either');
  });

  it('a driver error naming a relation reaches the client with only the stable BB name and message', async () => {
    const driverError = Object.assign(new Error('relation "customers_internal" does not exist (column ssn_hash)'), { code: '42P01' });

    const body = await rpc(async () => translatePgError(driverError, 'test'));
    assert.ok(body.error, 'the call must fail');
    assertNoSchema(body.raw);
    assert.ok(!body.raw.includes('does not exist'), 'raw driver text must not reach the client');
    // The BB error name still crosses the wire so clients can branch on it.
    assert.strictEqual(body.error.data?.name, DatabaseErrors.QueryFailed);
    const clientSide = Object.assign(new Error(body.error.message), { name: body.error.data?.name ?? '' });
    assert.ok(isBlocksError(clientSide, DatabaseErrors.QueryFailed));
  });

  it('a unique-constraint violation naming the constraint is surfaced as a stable 409', async () => {
    const driverError = Object.assign(
      new Error('duplicate key value violates unique constraint "customers_internal_email_key"'),
      { code: '23505', constraint: 'customers_internal_email_key' },
    );
    const body = await rpc(async () => translatePgError(driverError, 'test'));
    assert.ok(body.error, 'the call must fail');
    assertNoSchema(body.raw);
    assert.ok(!body.raw.includes('_key'), 'the constraint name must not reach the client');
  });
});
