// Generated from ./migrations — do not edit. Regenerated on migration change.
import type { Notes } from './database.types.js';

export const tableMeta = {
  notes: {
    singular: 'note',
    plural: 'notes',
    primaryKey: 'id',
    columns: ['id', 'text', 'done', 'created_at', 'owner'],
    autoGenerated: ['id', 'created_at', 'owner'],
    optional: ['done'],
  },
} as const;

export type TableMeta = {
  notes: { row: Notes; singular: 'note'; plural: 'notes'; autoGenerated: 'id' | 'created_at' | 'owner'; optional: 'done' };
};
