// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * The migration rewriter: turns ordinary PostgreSQL migration files into a
 * plan the target cluster accepts. The DSQL rewrites (identity columns, async
 * indexes, `NOT VALID` checks, one DDL per transaction) apply only to
 * `distributed`; other kinds run the files as written, minus `ASYNC`.
 */
import { brandBlocksError } from '@aws-blocks/core';
import { DOLLAR_QUOTE_TAG_RE, splitStatements } from '@aws-blocks/data-common';
import { DSQL_IDENTITY_CACHE } from '../constants.js';
import type { ClusterKind, FilePlan, MigrationPlan, PlanStep } from '../types.js';
import { classifyStatement, findStatementIssues, stripLiteralsAndComments } from '../validation.js';

/** Error name for a migration directory the target cluster cannot run. */
export const MIGRATION_VALIDATION_ERROR_NAME = 'DsqlMigrationValidationError';

interface Segment {
	text: string;
	literal: boolean;
}

/** Split SQL into literal (quoted / dollar-quoted / comment) and code segments so rewrites never touch literals. */
function segments(sql: string): Segment[] {
	const out: Segment[] = [];
	let code = '';
	let i = 0;
	const flushCode = () => {
		if (code) out.push({ text: code, literal: false });
		code = '';
	};
	while (i < sql.length) {
		if (sql[i] === '-' && sql[i + 1] === '-') {
			const nl = sql.indexOf('\n', i);
			const end = nl === -1 ? sql.length : nl + 1;
			flushCode();
			out.push({ text: sql.slice(i, end), literal: true });
			i = end;
			continue;
		}
		if (sql[i] === '/' && sql[i + 1] === '*') {
			const close = sql.indexOf('*/', i + 2);
			const end = close === -1 ? sql.length : close + 2;
			flushCode();
			out.push({ text: sql.slice(i, end), literal: true });
			i = end;
			continue;
		}
		if (sql[i] === "'") {
			let j = i + 1;
			while (j < sql.length) {
				if (sql[j] === "'" && sql[j + 1] === "'") j += 2;
				else if (sql[j] === "'") {
					j++;
					break;
				} else j++;
			}
			flushCode();
			out.push({ text: sql.slice(i, j), literal: true });
			i = j;
			continue;
		}
		if (sql[i] === '$') {
			const m = sql.slice(i).match(DOLLAR_QUOTE_TAG_RE);
			if (m) {
				const tag = m[0];
				const close = sql.indexOf(tag, i + tag.length);
				const end = close === -1 ? sql.length : close + tag.length;
				flushCode();
				out.push({ text: sql.slice(i, end), literal: true });
				i = end;
				continue;
			}
		}
		code += sql[i];
		i++;
	}
	flushCode();
	return out;
}

/** Apply a regex replacement to the non-literal parts of a statement only. */
export function replaceOutsideLiterals(sql: string, pattern: RegExp, replacement: string): string {
	return segments(sql)
		.map((s) => (s.literal ? s.text : s.text.replace(pattern, replacement)))
		.join('');
}

const SERIAL_TYPES: Record<string, string> = { SMALLSERIAL: 'SMALLINT', SERIAL: 'INTEGER', BIGSERIAL: 'BIGINT' };

/** `SERIAL` family → identity column with the DSQL-required cache. */
function rewriteSerial(sql: string): { sql: string; note?: string } {
	const pattern = /\b(SMALLSERIAL|BIGSERIAL|SERIAL)\b/gi;
	if (!pattern.test(stripLiteralsAndComments(sql))) return { sql };
	const rewritten = replaceOutsideLiterals(sql, /\b(SMALLSERIAL|BIGSERIAL|SERIAL)\b/gi, `__SERIAL__$1__`).replace(
		/__SERIAL__(\w+)__/g,
		(_m, t: string) => {
			return `${SERIAL_TYPES[t.toUpperCase()]} GENERATED BY DEFAULT AS IDENTITY (CACHE ${DSQL_IDENTITY_CACHE})`;
		},
	);
	return { sql: rewritten, note: `SERIAL rewritten to an identity column with CACHE ${DSQL_IDENTITY_CACHE}` };
}

const CREATE_INDEX = /^\s*CREATE\s+(UNIQUE\s+)?INDEX\b/i;
const CREATE_INDEX_ASYNC = /^\s*CREATE\s+(UNIQUE\s+)?INDEX\s+ASYNC\b/i;
const CREATE_INDEX_CONCURRENTLY = /^\s*CREATE\s+(UNIQUE\s+)?INDEX\s+CONCURRENTLY\b/i;
const ADD_CHECK_CONSTRAINT =
	/^\s*ALTER\s+TABLE\s+(?:IF\s+EXISTS\s+)?(?:ONLY\s+)?((?:"[^"]+"|[\w.]+))\s+ADD\s+CONSTRAINT\s+((?:"[^"]+"|\w+))\s+CHECK\b/i;
const FK_PATTERN =
	/\bREFERENCES\s+((?:"[^"]+"|[\w.]+))\s*(\([^)]*\))?((?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|RESTRICT|NO\s+ACTION|SET\s+NULL|SET\s+DEFAULT))*)/gi;

/** List every foreign key a statement defines together with its referential action. */
export function foreignKeysOf(statement: string): string[] {
	const cleaned = stripLiteralsAndComments(statement);
	const out: string[] = [];
	for (const m of cleaned.matchAll(FK_PATTERN)) {
		const actions = m[3]?.replace(/\s+/g, ' ').trim();
		out.push(`REFERENCES ${m[1]}${m[2] ?? ''}${actions ? ` ${actions}` : ' (NO ACTION)'}`);
	}
	return out;
}

interface Rewritten {
	steps: PlanStep[];
}

/** Rewrite one statement for the target, producing one or more plan steps. */
function rewriteStatement(statement: string, target: ClusterKind): Rewritten {
	const distributed = target === 'distributed';
	const cleaned = stripLiteralsAndComments(statement);

	if (!distributed) {
		// Portable: strip DSQL-only ASYNC; CONCURRENTLY cannot run inside a transaction.
		if (CREATE_INDEX_ASYNC.test(cleaned)) {
			const sql = replaceOutsideLiterals(statement, /\b(CREATE\s+(?:UNIQUE\s+)?INDEX)\s+ASYNC\b/i, '$1');
			return { steps: [{ kind: 'statement', sql, transactional: true, note: 'ASYNC (DSQL-only) removed' }] };
		}
		const transactional = !CREATE_INDEX_CONCURRENTLY.test(cleaned);
		return { steps: [{ kind: 'statement', sql: statement, transactional }] };
	}

	const isDdl = classifyStatement(statement) === 'ddl';
	let sql = statement;
	let note: string | undefined;

	const serial = rewriteSerial(sql);
	sql = serial.sql;
	note = serial.note;

	if (CREATE_INDEX.test(cleaned)) {
		if (!CREATE_INDEX_ASYNC.test(cleaned)) {
			sql = replaceOutsideLiterals(sql, /\b(CREATE\s+(?:UNIQUE\s+)?INDEX)\b/i, '$1 ASYNC');
			note = 'CREATE INDEX rewritten to CREATE INDEX ASYNC';
		}
		return {
			steps: [
				{ kind: 'statement', sql, transactional: false, note },
				{ kind: 'wait-index-job', sql: 'CALL sys.wait_for_job($job)', transactional: false },
			],
		};
	}

	const check = ADD_CHECK_CONSTRAINT.exec(cleaned);
	if (check) {
		const [, table, constraint] = check;
		if (!/\bNOT\s+VALID\s*$/i.test(cleaned.trim())) {
			sql = `${sql.trimEnd()} NOT VALID`;
			note = 'constraint added NOT VALID, validated in a separate step';
		}
		return {
			steps: [
				{ kind: 'statement', sql, transactional: false, note },
				{
					kind: 'validate-constraint',
					sql: `ALTER TABLE ${table} VALIDATE CONSTRAINT ${constraint}`,
					transactional: false,
				},
			],
		};
	}

	return { steps: [{ kind: 'statement', sql, transactional: !isDdl, note }] };
}

/**
 * Build the plan for a set of migration files (name → SQL) against a cluster
 * kind. Throws a branded `DsqlMigrationValidationError` listing every statement
 * the target cannot run, each with the file name and the doc page checked.
 */
export function buildMigrationPlan(migrations: Record<string, string>, target: ClusterKind): MigrationPlan {
	const errors: string[] = [];
	const files: FilePlan[] = [];
	for (const file of Object.keys(migrations).sort()) {
		const statements = splitStatements(migrations[file]);
		const steps: PlanStep[] = [];
		const foreignKeys: string[] = [];
		for (const statement of statements) {
			if (target === 'distributed') {
				for (const issue of findStatementIssues(statement)) {
					errors.push(`${file}: ${issue.message} Checked against ${issue.doc}`);
				}
			}
			foreignKeys.push(...foreignKeysOf(statement));
			steps.push(...rewriteStatement(statement, target).steps);
		}
		files.push({ file, steps, foreignKeys });
	}
	if (errors.length > 0) {
		const err = new Error(`Migration validation failed for a '${target}' cluster:\n  ${errors.join('\n  ')}`);
		err.name = MIGRATION_VALIDATION_ERROR_NAME;
		throw brandBlocksError(err);
	}
	return { target, files };
}

/** Render a plan the way `bb-database migrate --explain` prints it. */
export function formatMigrationPlan(plan: MigrationPlan, options: { pending?: Set<string> } = {}): string {
	const lines: string[] = [`Migration plan (target: ${plan.target})`];
	if (plan.files.length === 0) lines.push('  (no migration files)');
	for (const file of plan.files) {
		const status = options.pending ? (options.pending.has(file.file) ? 'pending' : 'applied') : '';
		lines.push(`\n${file.file}${status ? ` [${status}]` : ''}`);
		let txOpen = false;
		file.steps.forEach((step, i) => {
			if (step.transactional && !txOpen) {
				lines.push('  BEGIN');
				txOpen = true;
			}
			if (!step.transactional && txOpen) {
				lines.push('  COMMIT');
				txOpen = false;
			}
			const indent = step.transactional ? '    ' : '  ';
			const label = step.kind === 'statement' ? '' : `[${step.kind}] `;
			lines.push(
				`${indent}${i + 1}. ${label}${step.sql.replace(/\s+/g, ' ').trim()}${step.note ? `  -- ${step.note}` : ''}`,
			);
		});
		if (txOpen) lines.push('  COMMIT');
		lines.push(`  record ${file.file} in _migrations`);
		if (file.foreignKeys.length > 0) {
			lines.push('  foreign keys and their referential actions:');
			for (const fk of file.foreignKeys) lines.push(`    - ${fk}`);
		}
	}
	return lines.join('\n');
}
