#!/usr/bin/env bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generates the committed Swift version constant (Version.swift) from
# package.json. It is committed because SwiftPM consumers build our source and
# never run this script.
#
# Usage:
#   generate-version.sh            writes the constant
#   generate-version.sh --check    verifies it is current (CI), no write
#
# --check is load bearing: a stale constant fails no build and passes every
# test, so nothing else catches it drifting from the package version.

set -euo pipefail

CHECK=false
if [[ "${1:-}" == "--check" ]]; then
  CHECK=true
elif [[ -n "${1:-}" ]]; then
  echo "Usage: generate-version.sh [--check]" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# PROJECT_DIR defaults to the package root (parent of scripts/) but can be
# overridden (e.g. by tests) to point at a fixture directory.
PROJECT_DIR="${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"

PKG_JSON="$PROJECT_DIR/package.json"
SWIFTFORMAT="$PROJECT_DIR/.swiftformat"
TARGET="$PROJECT_DIR/Sources/BlocksRuntime/Version.swift"

VERSION=$(node -p "require('$PKG_JSON').version")

# The version half of the token grammar: N.N.N, optional -prerelease, no build metadata.
if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]{1,20})?$ ]]; then
  echo "Version \"$VERSION\" in package.json is not a valid token semver (N.N.N, optional -prerelease, no build metadata)." >&2
  exit 1
fi

# Read the licence header from .swiftformat rather than duplicating it, so
# swiftformat and this generator cannot demand different headers. The option
# encodes line breaks as the two characters backslash and n.
if [[ ! -f "$SWIFTFORMAT" ]]; then
  echo "Cannot read $SWIFTFORMAT. The Swift licence header lives there." >&2
  exit 1
fi
HEADER_RAW=$(sed -nE 's/^--header "(.*)"[[:space:]]*$/\1/p' "$SWIFTFORMAT" | head -1)
if [[ -z "$HEADER_RAW" ]]; then
  echo "No quoted --header value in $SWIFTFORMAT to use as the Swift licence header." >&2
  exit 1
fi
HEADER="${HEADER_RAW//\\n/$'\n'}"

EXPECTED="$(cat <<EOF
$HEADER

// Auto-generated by native/swift/scripts/generate-version.sh. Do not edit manually.
// Source of truth: native/swift/package.json

/// Semver of this AWS Blocks Swift runtime library.
let blocksRuntimeVersion = "$VERSION"

/// The user agent token for this runtime, e.g. \`aws-blocks-swift/$VERSION\`.
/// Keep the \`aws-blocks\` prefix: rows without it do not appear in reporting.
let blocksUserAgentToken = "aws-blocks-swift/\(blocksRuntimeVersion)"
EOF
)"

if [[ "$CHECK" == true ]]; then
  # Normalize CRLF so a Windows checkout (core.autocrlf) does not report false drift.
  if [[ -f "$TARGET" ]] && [[ "$(tr -d '\r' < "$TARGET")" == "$EXPECTED" ]]; then
    echo "ok: $TARGET matches package.json ($VERSION)"
    exit 0
  fi
  if [[ -f "$TARGET" ]]; then
    echo "DRIFT: $TARGET does not match package.json ($VERSION)." >&2
  else
    echo "DRIFT: $TARGET is missing." >&2
  fi
  echo "       Run: native/swift/scripts/generate-version.sh" >&2
  exit 1
fi

printf '%s\n' "$EXPECTED" > "$TARGET"
echo "Generated $TARGET ($VERSION)"
