// AUTO-GENERATED by @aws-blocks/hosting typegen — DO NOT EDIT.
// Regenerate with `npm run typegen`. It narrows getSecret()/getConfig() to your
// declared secret()/config() keys. Deleting it is safe — the keys fall back to `string`.

export {};

declare module "@aws-blocks/hosting" {
	interface HostingSecretRegistry {
		"DEMO_SECRET": string;
	}

	interface HostingConfigRegistry {
		"DEMO_CONFIG": string;
	}
}
