// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, it } from 'node:test';
import type { TableSchema } from '../crud/types.js';
import { PGliteEngine } from '../engines/pglite-engine.js';
import { createDataClient } from './index.js';
import type { TableTypeMeta } from './types.js';

// Shaped exactly like the output of `@aws-blocks/bb-data/schema-sync`: no index
// signature, so column names are actually checkable.
interface Note {
	id: number;
	text: string;
	done: boolean;
	priority: number;
	label: string | null;
	created_at: Date;
}

interface Schema extends Record<string, TableTypeMeta> {
	notes: {
		row: Note;
		singular: 'note';
		plural: 'notes';
		/** Server-managed: a serial and a `DEFAULT now()`. */
		autoGenerated: 'id' | 'created_at';
		/** Settable but omittable: defaults, plus a nullable column. */
		optional: 'done' | 'priority' | 'label';
	};
}

const schema: TableSchema = {
	notes: {
		singular: 'note',
		plural: 'notes',
		primaryKey: 'id',
		columns: ['id', 'text', 'done', 'priority', 'label', 'created_at'],
		autoGenerated: ['id', 'created_at'],
	},
};

let dir: string;
let engine: PGliteEngine;
let data: ReturnType<typeof createDataClient<Schema>>;

beforeEach(async () => {
	dir = mkdtempSync(join(tmpdir(), 'fluent-test-'));
	engine = new PGliteEngine(dir);
	await engine.execute(`CREATE TABLE notes (
		id SERIAL PRIMARY KEY,
		text TEXT NOT NULL,
		done BOOLEAN NOT NULL DEFAULT FALSE,
		priority INTEGER NOT NULL DEFAULT 0,
		label TEXT,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now()
	)`);
	data = createDataClient<Schema>({ getEngine: async () => engine }, schema);
});

afterEach(async () => {
	await engine.destroy();
	rmSync(dir, { recursive: true, force: true });
});

const seed = async (rows: Array<{ text: string; done?: boolean; priority?: number }>) => {
	for (const row of rows) await data.from('notes').insert(row);
};

describe('fluent client: reads', () => {
	it('returns every row and column when awaited directly', async () => {
		await seed([{ text: 'a' }, { text: 'b' }]);
		const rows = await data.from('notes').select();

		assert.equal(rows.length, 2);
		assert.deepEqual(Object.keys(rows[0]).sort(), ['created_at', 'done', 'id', 'label', 'priority', 'text']);
	});

	it('narrows the returned columns', async () => {
		await seed([{ text: 'a' }]);
		const rows = await data.from('notes').select('id', 'text');
		assert.deepEqual(Object.keys(rows[0]).sort(), ['id', 'text']);
	});

	it('filters with eq', async () => {
		await seed([{ text: 'open' }, { text: 'closed', done: true }]);
		const rows = await data.from('notes').select('text').eq('done', true);
		assert.deepEqual(rows, [{ text: 'closed' }]);
	});

	it('combines range operators on one column', async () => {
		await seed([{ text: 'p1', priority: 1 }, { text: 'p5', priority: 5 }, { text: 'p9', priority: 9 }]);
		const rows = await data.from('notes').select('text').gte('priority', 2).lte('priority', 8);
		assert.deepEqual(rows, [{ text: 'p5' }]);
	});

	it('supports in, like and ilike', async () => {
		await seed([{ text: 'Alpha' }, { text: 'beta' }, { text: 'gamma' }]);

		assert.equal((await data.from('notes').select('text').in('text', ['Alpha', 'gamma'])).length, 2);
		assert.equal((await data.from('notes').select('text').like('text', 'A%')).length, 1);
		assert.equal((await data.from('notes').select('text').ilike('text', 'a%')).length, 1);
	});

	it('treats eq(column, null) as IS NULL', async () => {
		await data.from('notes').insert({ text: 'has', label: 'x' });
		await data.from('notes').insert({ text: 'none' });

		const rows = await data.from('notes').select('text').eq('label', null);
		assert.deepEqual(rows, [{ text: 'none' }]);
	});

	it('orders, limits and offsets', async () => {
		await seed([{ text: 'a', priority: 1 }, { text: 'b', priority: 2 }, { text: 'c', priority: 3 }]);

		const desc = await data.from('notes').select('text').order('priority', 'desc');
		assert.deepEqual(desc.map((r) => r.text), ['c', 'b', 'a']);

		const paged = await data.from('notes').select('text').order('priority').limit(1).offset(1);
		assert.deepEqual(paged, [{ text: 'b' }]);
	});

	it('sorts by several columns in call order', async () => {
		await seed([
			{ text: 'b', priority: 1 },
			{ text: 'a', priority: 1 },
			{ text: 'c', priority: 0 },
		]);
		const rows = await data.from('notes').select('text').order('priority').order('text');
		assert.deepEqual(rows.map((r) => r.text), ['c', 'a', 'b']);
	});

	it('first() returns a row, or null when nothing matches', async () => {
		await seed([{ text: 'only' }]);
		assert.equal((await data.from('notes').select('text').first())?.text, 'only');

		// Not-found is ordinary control flow, so this is null rather than a throw.
		assert.equal(await data.from('notes').select('text').eq('text', 'absent').first(), null);
	});

	it('count() ignores select, order and limit', async () => {
		await seed([{ text: 'a' }, { text: 'b' }, { text: 'c' }]);
		assert.equal(await data.from('notes').select('id').limit(1).count(), 3);
		assert.equal(await data.from('notes').select().eq('done', true).count(), 0);
	});

	it('runs the query once even when awaited twice', async () => {
		await seed([{ text: 'a' }]);
		const query = data.from('notes').select('text');

		const [first, second] = [await query, await query];
		assert.deepEqual(first, second);
	});
});

describe('fluent client: writes', () => {
	it('insert returns the stored row including generated values', async () => {
		const note = await data.from('notes').insert({ text: 'written', done: false, priority: 3 });

		assert.equal(note.text, 'written');
		assert.equal(note.priority, 3);
		assert.ok(Number.isInteger(note.id), 'expected a generated id');
		assert.ok(note.created_at instanceof Date, 'expected a generated timestamp');
	});

	it('update applies to matching rows and returns them', async () => {
		await seed([{ text: 'a' }, { text: 'b' }]);

		const updated = await data.from('notes').update({ done: true }).eq('text', 'a');
		assert.equal(updated.length, 1);
		assert.equal(updated[0].done, true);
		assert.equal(await data.from('notes').select().eq('done', true).count(), 1);
	});

	it('delete removes matching rows and returns them', async () => {
		await seed([{ text: 'a' }, { text: 'b' }]);

		const deleted = await data.from('notes').delete().eq('text', 'a');
		assert.deepEqual(deleted.map((r) => r.text), ['a']);
		assert.equal(await data.from('notes').select().count(), 1);
	});

	it('refuses an unfiltered update', async () => {
		await seed([{ text: 'a' }, { text: 'b' }]);

		// A forgotten filter must not rewrite the whole table.
		await assert.rejects(() => data.from('notes').update({ done: true }), /requires at least one filter/);
		assert.equal(await data.from('notes').select().eq('done', true).count(), 0);
	});

	it('refuses an unfiltered delete', async () => {
		await seed([{ text: 'a' }, { text: 'b' }]);

		await assert.rejects(() => data.from('notes').delete(), /requires at least one filter/);
		assert.equal(await data.from('notes').select().count(), 2);
	});

	it('ignores auto-generated columns supplied on insert', async () => {
		// A caller must not be able to choose a serial id or forge created_at.
		const note = await data.from('notes').insert({ text: 'x', id: 999, created_at: new Date(0) } as never);
		assert.notEqual(note.id, 999);
		assert.notEqual(note.created_at.getTime(), 0);
	});
});

describe('fluent client: rejects unknown identifiers', () => {
	it('rejects an unknown table', () => {
		assert.throws(() => data.from('nope' as never), /Unknown table: "nope"/);
	});

	it('rejects an unknown column in select', async () => {
		await assert.rejects(() => data.from('notes').select('nope' as never), /Unknown column: "nope"/);
	});

	it('rejects an unknown column in a filter', async () => {
		// The casts stand in for a plain-JS caller: the compiler already rejects this,
		// so the runtime check is the second line of defence.
		await assert.rejects(
			() => data.from('notes').select().eq('nope' as never, 1 as never),
			/Unknown column: "nope"/,
		);
	});

	it('rejects an empty in() list rather than emitting invalid SQL', async () => {
		await assert.rejects(() => data.from('notes').select().in('text', []), /non-empty array/);
	});

	it('parameterizes values instead of interpolating them', async () => {
		// The classic injection attempt has to be stored as data, not executed.
		const evil = "'; DROP TABLE notes; --";
		await data.from('notes').insert({ text: evil });

		const found = await data.from('notes').select('text').eq('text', evil).first();
		assert.equal(found?.text, evil);
		assert.equal(await data.from('notes').select().count(), 1);
	});
});

describe('fluent client: behaves like a real promise', () => {
	// A `then`-only thenable awaits fine but breaks the moment anyone reaches for
	// .catch(), .finally(), or an API that expects a genuine Promise.
	it('supports .catch()', async () => {
		const caught = await data
			.from('notes')
			.select('nope' as never)
			.catch(() => 'caught');
		assert.equal(caught, 'caught');
	});

	it('supports .finally()', async () => {
		let ran = false;
		await data
			.from('notes')
			.select('id')
			.finally(() => {
				ran = true;
			});
		assert.equal(ran, true);
	});

	it('works with Promise.all', async () => {
		await seed([{ text: 'a' }, { text: 'b' }]);
		const [all, done] = await Promise.all([
			data.from('notes').select('text'),
			data.from('notes').select('text').eq('done', true),
		]);
		assert.equal(all.length, 2);
		assert.equal(done.length, 0);
	});

	it('reports as a Promise to instanceof-style checks', () => {
		const query = data.from('notes').select('id');
		assert.equal(Object.prototype.toString.call(query), '[object Promise]');
	});
});
