// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Public types for the fluent query client.
 *
 * @module
 */

import type { DatabaseEngine } from '@aws-blocks/data-common';

/** Anything that can run parameterized SQL. A `Database` satisfies this. */
export interface EngineProvider {
	/** @internal */
	getEngine(): Promise<DatabaseEngine>;
}

/**
 * Type-level description of one table, as emitted in the generated `TableMeta`.
 *
 * Deliberately constrains `row` to `object` rather than `Record<string, unknown>`,
 * which is what `db.crud<M>()` requires. An interface only satisfies
 * `Record<string, unknown>` by declaring `[key: string]: unknown`, and that index
 * signature makes `keyof Row` include `string` — which would silently defeat every
 * column-name check in this client. Checkable column names are the point, so the
 * looser constraint is the correct one here.
 */
export interface TableTypeMeta {
	row: object;
	singular: string;
	plural: string;
	/** Server-managed columns (serial, `DEFAULT now()`, …). Not settable by a caller. */
	autoGenerated: string;
	/** Columns with a default or that are nullable: settable, but omittable. */
	optional: string;
}

/** Sort direction for {@link SelectQuery.order}. */
export type SortDirection = 'asc' | 'desc';

/** The row type of table `T` in schema `M`. */
export type RowOf<M extends Record<string, TableTypeMeta>, T extends keyof M> = M[T]['row'];

/**
 * What a caller may pass to `insert`.
 *
 * Server-managed columns are excluded outright, columns with a default or that are
 * nullable become optional, and everything else stays required — matching what
 * Postgres will actually accept.
 */
export type InsertOf<M extends Record<string, TableTypeMeta>, T extends keyof M> = Omit<
	RowOf<M, T>,
	M[T]['autoGenerated'] | M[T]['optional']
> &
	Partial<Pick<RowOf<M, T>, Extract<M[T]['optional'], keyof RowOf<M, T>>>>;

/**
 * A SELECT under construction.
 *
 * Awaiting it runs the query and resolves to the rows. Filters and modifiers can be
 * chained in any order; `select()` narrows the result type to the named columns.
 *
 * Errors throw rather than being returned — match them with `isBlocksError`.
 */
export interface SelectQuery<Row, Selected> extends Promise<Selected[]> {
	/**
	 * Restrict the columns returned, narrowing the result type to match.
	 *
	 * Unknown column names are a compile error, and are rejected at runtime against
	 * the introspected schema as well.
	 */
	select<K extends keyof Row & string>(...columns: K[]): SelectQuery<Row, Pick<Row, K>>;

	/** `column = value`. Pass `null` for `IS NULL`. */
	eq<K extends keyof Row & string>(column: K, value: Row[K] | null): SelectQuery<Row, Selected>;
	/** `column > value`. */
	gt<K extends keyof Row & string>(column: K, value: Row[K]): SelectQuery<Row, Selected>;
	/** `column >= value`. */
	gte<K extends keyof Row & string>(column: K, value: Row[K]): SelectQuery<Row, Selected>;
	/** `column < value`. */
	lt<K extends keyof Row & string>(column: K, value: Row[K]): SelectQuery<Row, Selected>;
	/** `column <= value`. */
	lte<K extends keyof Row & string>(column: K, value: Row[K]): SelectQuery<Row, Selected>;
	/** `column LIKE pattern` (case-sensitive). */
	like<K extends keyof Row & string>(column: K, pattern: string): SelectQuery<Row, Selected>;
	/** `column ILIKE pattern` (case-insensitive). */
	ilike<K extends keyof Row & string>(column: K, pattern: string): SelectQuery<Row, Selected>;
	/** `column IN (...values)`. Throws on an empty array rather than emitting invalid SQL. */
	in<K extends keyof Row & string>(column: K, values: Row[K][]): SelectQuery<Row, Selected>;

	/** Append an ORDER BY term. Call more than once to sort by several columns. */
	order(column: keyof Row & string, direction?: SortDirection): SelectQuery<Row, Selected>;
	/** LIMIT. Must be a non-negative integer. */
	limit(count: number): SelectQuery<Row, Selected>;
	/** OFFSET. Must be a non-negative integer. */
	offset(count: number): SelectQuery<Row, Selected>;

	/**
	 * Run the query and return the first row, or `null` when there are none.
	 *
	 * Applies `LIMIT 1`. Returns `null` rather than throwing, because "not found" is
	 * ordinary control flow.
	 */
	first(): Promise<Selected | null>;

	/** Number of matching rows, ignoring `select`, `order`, `limit` and `offset`. */
	count(): Promise<number>;
}

/** A write under construction. Requires at least one filter before it will run. */
export interface WriteQuery<Row> extends Promise<Row[]> {
	/** `column = value`. Pass `null` for `IS NULL`. */
	eq<K extends keyof Row & string>(column: K, value: Row[K] | null): WriteQuery<Row>;
	/** `column IN (...values)`. */
	in<K extends keyof Row & string>(column: K, values: Row[K][]): WriteQuery<Row>;
	/** `column > value`. */
	gt<K extends keyof Row & string>(column: K, value: Row[K]): WriteQuery<Row>;
	/** `column < value`. */
	lt<K extends keyof Row & string>(column: K, value: Row[K]): WriteQuery<Row>;
}

/** Query entry point for one table. */
export interface TableQuery<M extends Record<string, TableTypeMeta>, T extends keyof M> {
	/** Start a SELECT. Without `.select(...)` every column is returned. */
	select(): SelectQuery<RowOf<M, T>, RowOf<M, T>>;
	select<K extends keyof RowOf<M, T> & string>(
		...columns: K[]
	): SelectQuery<RowOf<M, T>, Pick<RowOf<M, T>, K>>;

	/**
	 * Insert one row and return it as stored, including database-generated values.
	 *
	 * Auto-generated columns are rejected at compile time and stripped at runtime, so
	 * a serial id or `DEFAULT now()` cannot be overwritten by a caller.
	 */
	insert(values: InsertOf<M, T>): Promise<RowOf<M, T>>;

	/**
	 * Update matching rows and return them.
	 *
	 * Requires at least one filter: `update({...}).eq('id', 1)`. An unfiltered update
	 * throws instead of rewriting the whole table.
	 */
	update(values: Partial<InsertOf<M, T>>): WriteQuery<RowOf<M, T>>;

	/**
	 * Delete matching rows and return them.
	 *
	 * Requires at least one filter, for the same reason as {@link TableQuery.update}.
	 */
	delete(): WriteQuery<RowOf<M, T>>;
}

/** A typed, schema-aware query client. Create one with `createDataClient`. */
export interface DataClient<M extends Record<string, TableTypeMeta>> {
	/** Target a table. Unknown table names are a compile error. */
	from<T extends keyof M & string>(table: T): TableQuery<M, T>;
}
