// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Browser half of the data API.
 *
 * Mirrors the server-side fluent client's shape, so the same query reads the same in a
 * Server Component and in a Client Component — but here every call only accumulates a
 * description, which the transport posts to the single server endpoint.
 *
 * Safe to import into browser code: this module touches no database driver and holds no
 * connection details. There is no URL and no API key to leak or rotate, because the
 * transport rides the app's existing session.
 *
 * @module
 */

import type {
	DataApiOperator,
	QueryDescription,
	ScalarValue,
	SerializedFilter,
	SerializedOrder,
} from './types.js';

/** Type-level table description, matching the generated `TableMeta`. */
export interface ClientTableMeta {
	row: object;
	autoGenerated: string;
	optional: string;
}

/** Sends a validated description to the server and resolves the rows. */
export type DataApiTransport = (query: QueryDescription) => Promise<unknown[]>;

type RowOf<M extends Record<string, ClientTableMeta>, T extends keyof M> = M[T]['row'];

type InsertOf<M extends Record<string, ClientTableMeta>, T extends keyof M> = Omit<
	RowOf<M, T>,
	M[T]['autoGenerated'] | M[T]['optional']
> &
	Partial<Pick<RowOf<M, T>, Extract<M[T]['optional'], keyof RowOf<M, T>>>>;

/** A browser-issued SELECT under construction. */
export interface RemoteSelect<Row, Selected> extends Promise<Selected[]> {
	select<K extends keyof Row & string>(...columns: K[]): RemoteSelect<Row, Pick<Row, K>>;
	eq<K extends keyof Row & string>(column: K, value: Row[K] | null): RemoteSelect<Row, Selected>;
	gt<K extends keyof Row & string>(column: K, value: Row[K]): RemoteSelect<Row, Selected>;
	gte<K extends keyof Row & string>(column: K, value: Row[K]): RemoteSelect<Row, Selected>;
	lt<K extends keyof Row & string>(column: K, value: Row[K]): RemoteSelect<Row, Selected>;
	lte<K extends keyof Row & string>(column: K, value: Row[K]): RemoteSelect<Row, Selected>;
	like<K extends keyof Row & string>(column: K, pattern: string): RemoteSelect<Row, Selected>;
	ilike<K extends keyof Row & string>(column: K, pattern: string): RemoteSelect<Row, Selected>;
	in<K extends keyof Row & string>(column: K, values: Row[K][]): RemoteSelect<Row, Selected>;
	order(column: keyof Row & string, direction?: 'asc' | 'desc'): RemoteSelect<Row, Selected>;
	limit(count: number): RemoteSelect<Row, Selected>;
	offset(count: number): RemoteSelect<Row, Selected>;
	/** First row, or `null` when there are none. */
	first(): Promise<Selected | null>;
	/** Number of matching rows. */
	count(): Promise<number>;
}

/** A browser-issued write under construction. Requires a filter. */
export interface RemoteWrite<Row> extends Promise<Row[]> {
	eq<K extends keyof Row & string>(column: K, value: Row[K] | null): RemoteWrite<Row>;
	in<K extends keyof Row & string>(column: K, values: Row[K][]): RemoteWrite<Row>;
}

/** Query entry point for one table. */
export interface RemoteTable<M extends Record<string, ClientTableMeta>, T extends keyof M> {
	select(): RemoteSelect<RowOf<M, T>, RowOf<M, T>>;
	select<K extends keyof RowOf<M, T> & string>(
		...columns: K[]
	): RemoteSelect<RowOf<M, T>, Pick<RowOf<M, T>, K>>;
	insert(values: InsertOf<M, T>): Promise<RowOf<M, T>>;
	update(values: Partial<InsertOf<M, T>>): RemoteWrite<RowOf<M, T>>;
	delete(): RemoteWrite<RowOf<M, T>>;
}

/** A typed browser data client. */
export interface RemoteDataClient<M extends Record<string, ClientTableMeta>> {
	from<T extends keyof M & string>(table: T): RemoteTable<M, T>;
}

/**
 * Create a browser data client.
 *
 * Table and column names are checked at compile time against the generated schema, so
 * unlike a stringly-typed `select('id, text')` a typo is a build error.
 *
 * @example
 * ```ts
 * export const data = createRemoteDataClient<TableMeta>(async (query) => {
 *   const res = await fetch('/api/data', {
 *     method: 'POST',
 *     headers: { 'Content-Type': 'application/json' },
 *     body: JSON.stringify(query),
 *   });
 *   if (!res.ok) throw new Error((await res.json()).message);
 *   return res.json();
 * });
 *
 * const notes = await data.from('notes').select('id', 'text').eq('done', false);
 * ```
 */
export function createRemoteDataClient<M extends Record<string, ClientTableMeta>>(
	transport: DataApiTransport,
): RemoteDataClient<M> {
	return {
		from<T extends keyof M & string>(table: T): RemoteTable<M, T> {
			return {
				select<K extends keyof RowOf<M, T> & string>(...columns: K[]) {
					const query = new RemoteSelectImpl<RowOf<M, T>, RowOf<M, T>>(transport, table);
					return (columns.length > 0 ? query.select(...columns) : query) as RemoteSelect<
						RowOf<M, T>,
						Pick<RowOf<M, T>, K>
					>;
				},
				async insert(values: InsertOf<M, T>): Promise<RowOf<M, T>> {
					const rows = await transport({
						table,
						operation: 'insert',
						values: values as Record<string, ScalarValue>,
					});
					return rows[0] as RowOf<M, T>;
				},
				update(values: Partial<InsertOf<M, T>>): RemoteWrite<RowOf<M, T>> {
					return new RemoteWriteImpl<RowOf<M, T>>(transport, table, 'update', values as Record<string, ScalarValue>);
				},
				delete(): RemoteWrite<RowOf<M, T>> {
					return new RemoteWriteImpl<RowOf<M, T>>(transport, table, 'delete');
				},
			};
		},
	};
}

/** Shared promise plumbing: full `Promise` surface, executed at most once. */
abstract class RemoteQuery<T> implements Promise<T> {
	private pending?: Promise<T>;
	protected abstract run(): Promise<T>;

	private exec(): Promise<T> {
		this.pending ??= this.run();
		return this.pending;
	}

	then<R1 = T, R2 = never>(
		onfulfilled?: ((value: T) => R1 | PromiseLike<R1>) | null,
		onrejected?: ((reason: unknown) => R2 | PromiseLike<R2>) | null,
	): Promise<R1 | R2> {
		return this.exec().then(onfulfilled, onrejected);
	}

	catch<R = never>(onrejected?: ((reason: unknown) => R | PromiseLike<R>) | null): Promise<T | R> {
		return this.exec().catch(onrejected);
	}

	finally(onfinally?: (() => void) | null): Promise<T> {
		return this.exec().finally(onfinally);
	}

	readonly [Symbol.toStringTag] = 'Promise';
}

class RemoteSelectImpl<Row, Selected> extends RemoteQuery<Selected[]> implements RemoteSelect<Row, Selected> {
	private readonly filters: SerializedFilter[] = [];
	private readonly orderTerms: SerializedOrder[] = [];
	private columns?: string[];
	private limitValue?: number;
	private offsetValue?: number;

	constructor(
		private readonly transport: DataApiTransport,
		private readonly table: string,
	) {
		super();
	}

	select<K extends keyof Row & string>(...columns: K[]): RemoteSelect<Row, Pick<Row, K>> {
		this.columns = columns;
		// Only the compile-time result type changes.
		return this as unknown as RemoteSelect<Row, Pick<Row, K>>;
	}

	private filter(column: string, operator: DataApiOperator, value?: unknown) {
		// `is_null` carries no value; omit the key entirely rather than sending
		// `value: undefined`, which JSON would drop anyway.
		this.filters.push(
			value === undefined ? { column, operator } : { column, operator, value: value as ScalarValue },
		);
		return this;
	}

	eq<K extends keyof Row & string>(column: K, value: Row[K] | null) {
		return value === null ? this.filter(column, 'is_null') : this.filter(column, 'eq', value);
	}
	gt<K extends keyof Row & string>(column: K, value: Row[K]) {
		return this.filter(column, 'gt', value);
	}
	gte<K extends keyof Row & string>(column: K, value: Row[K]) {
		return this.filter(column, 'gte', value);
	}
	lt<K extends keyof Row & string>(column: K, value: Row[K]) {
		return this.filter(column, 'lt', value);
	}
	lte<K extends keyof Row & string>(column: K, value: Row[K]) {
		return this.filter(column, 'lte', value);
	}
	like<K extends keyof Row & string>(column: K, pattern: string) {
		return this.filter(column, 'like', pattern);
	}
	ilike<K extends keyof Row & string>(column: K, pattern: string) {
		return this.filter(column, 'ilike', pattern);
	}
	in<K extends keyof Row & string>(column: K, values: Row[K][]) {
		this.filters.push({ column, operator: 'in', value: values as ScalarValue[] });
		return this;
	}

	order(column: keyof Row & string, direction: 'asc' | 'desc' = 'asc') {
		this.orderTerms.push({ column, direction });
		return this;
	}

	limit(count: number) {
		this.limitValue = count;
		return this;
	}

	offset(count: number) {
		this.offsetValue = count;
		return this;
	}

	async first(): Promise<Selected | null> {
		const rows = await this.limit(1);
		return rows[0] ?? null;
	}

	async count(): Promise<number> {
		const rows = (await this.transport({
			table: this.table,
			operation: 'count',
			filters: this.filters,
		})) as Array<{ count: number }>;
		return rows[0]?.count ?? 0;
	}

	protected run(): Promise<Selected[]> {
		return this.transport({
			table: this.table,
			operation: 'select',
			columns: this.columns,
			filters: this.filters,
			order: this.orderTerms,
			limit: this.limitValue,
			offset: this.offsetValue,
		}) as Promise<Selected[]>;
	}
}

class RemoteWriteImpl<Row> extends RemoteQuery<Row[]> implements RemoteWrite<Row> {
	private readonly filters: SerializedFilter[] = [];

	constructor(
		private readonly transport: DataApiTransport,
		private readonly table: string,
		private readonly operation: 'update' | 'delete',
		private readonly values?: Record<string, ScalarValue>,
	) {
		super();
	}

	eq<K extends keyof Row & string>(column: K, value: Row[K] | null) {
		this.filters.push(
			value === null
				? { column, operator: 'is_null' }
				: { column, operator: 'eq', value: value as ScalarValue },
		);
		return this;
	}

	in<K extends keyof Row & string>(column: K, values: Row[K][]) {
		this.filters.push({ column, operator: 'in', value: values as ScalarValue[] });
		return this;
	}

	protected run(): Promise<Row[]> {
		// The server rejects an unfiltered update or delete; this is not enforced here,
		// because a client-side check is a convenience, not a control.
		return this.transport({
			table: this.table,
			operation: this.operation,
			values: this.values,
			filters: this.filters,
		}) as Promise<Row[]>;
	}
}
