// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * The data API is a public, internet-reachable endpoint that runs database queries, so
 * these tests are mostly about what it *refuses*.
 */

import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, it } from 'node:test';
import type { TableSchema } from '../crud/types.js';
import { RLSEnabledDatabase } from '../database.js';
import { PGliteEngine } from '../engines/pglite-engine.js';
import { createRemoteDataClient } from './client.js';
import { DataApiErrors } from './errors.js';
import { createDataApi, type DataApiUser } from './server.js';
import { validateQueryDescription } from './validate.js';

const schema: TableSchema = {
	notes: {
		singular: 'note',
		plural: 'notes',
		primaryKey: 'id',
		columns: ['id', 'owner', 'text', 'done', 'created_at'],
		autoGenerated: ['id', 'created_at'],
	},
	secrets: {
		singular: 'secret',
		plural: 'secrets',
		primaryKey: 'id',
		columns: ['id', 'value'],
		autoGenerated: ['id'],
	},
};

const validateIn = (raw: unknown, tables: readonly string[] = ['notes']) =>
	validateQueryDescription(raw, { schema, allowedTables: tables });

describe('query validation: allowlists', () => {
	it('accepts a well-formed select', () => {
		const query = validateIn({
			table: 'notes',
			operation: 'select',
			columns: ['id', 'text'],
			filters: [{ column: 'done', operator: 'eq', value: false }],
			order: [{ column: 'id', direction: 'desc' }],
			limit: 10,
		});
		assert.equal(query.table, 'notes');
		assert.deepEqual(query.columns, ['id', 'text']);
	});

	it('refuses a table that exists but was not exposed', () => {
		// The whole point of an opt-in list: `secrets` is in the schema, not the API.
		assert.throws(() => validateIn({ table: 'secrets', operation: 'select' }), {
			name: DataApiErrors.TableNotExposed,
		});
	});

	it('refuses a table that does not exist', () => {
		assert.throws(() => validateIn({ table: 'nope', operation: 'select' }), {
			name: DataApiErrors.TableNotExposed,
		});
	});

	it('refuses an unknown operation', () => {
		assert.throws(() => validateIn({ table: 'notes', operation: 'drop' }), { name: DataApiErrors.InvalidQuery });
	});

	it('refuses unknown columns everywhere they can appear', () => {
		const cases: unknown[] = [
			{ table: 'notes', operation: 'select', columns: ['nope'] },
			{ table: 'notes', operation: 'select', filters: [{ column: 'nope', operator: 'eq', value: 1 }] },
			{ table: 'notes', operation: 'select', order: [{ column: 'nope', direction: 'asc' }] },
			{ table: 'notes', operation: 'insert', values: { nope: 1 } },
		];
		for (const query of cases) {
			assert.throws(() => validateIn(query), { name: DataApiErrors.InvalidQuery }, JSON.stringify(query));
		}
	});

	it('refuses an unknown filter operator', () => {
		assert.throws(
			() => validateIn({ table: 'notes', operation: 'select', filters: [{ column: 'id', operator: 'raw', value: 1 }] }),
			{ name: DataApiErrors.InvalidQuery },
		);
	});

	it('refuses a non-scalar filter value', () => {
		// Objects are how an attacker would try to smuggle a nested operator through.
		for (const value of [{ gt: 1 }, [1, 2], () => 1]) {
			assert.throws(
				() =>
					validateIn({ table: 'notes', operation: 'select', filters: [{ column: 'id', operator: 'eq', value }] }),
				{ name: DataApiErrors.InvalidQuery },
			);
		}
	});

	it('refuses an invalid order direction', () => {
		assert.throws(
			() => validateIn({ table: 'notes', operation: 'select', order: [{ column: 'id', direction: 'sideways' }] }),
			{ name: DataApiErrors.InvalidQuery },
		);
	});
});

describe('query validation: limits and writes', () => {
	it('applies a default limit so a client cannot pull a whole table', () => {
		assert.equal(validateIn({ table: 'notes', operation: 'select' }).limit, 1000);
	});

	it('refuses a limit above the maximum', () => {
		assert.throws(
			() => validateQueryDescription({ table: 'notes', operation: 'select', limit: 50 }, {
				schema,
				allowedTables: ['notes'],
				maxLimit: 10,
			}),
			{ name: DataApiErrors.InvalidQuery },
		);
	});

	it('refuses a negative or fractional limit and offset', () => {
		for (const query of [
			{ table: 'notes', operation: 'select', limit: -1 },
			{ table: 'notes', operation: 'select', limit: 1.5 },
			{ table: 'notes', operation: 'select', offset: -1 },
		]) {
			assert.throws(() => validateIn(query), { name: DataApiErrors.InvalidQuery });
		}
	});

	it('refuses an update or delete with no filter', () => {
		// Otherwise a forgotten filter empties the table for every user the policy allows.
		assert.throws(() => validateIn({ table: 'notes', operation: 'update', values: { done: true } }), {
			name: DataApiErrors.InvalidQuery,
		});
		assert.throws(() => validateIn({ table: 'notes', operation: 'delete' }), { name: DataApiErrors.InvalidQuery });
	});

	it('refuses writes to database-managed columns', () => {
		// A client must not choose its own id or forge created_at.
		for (const values of [{ id: 1 }, { created_at: '2020-01-01' }]) {
			assert.throws(() => validateIn({ table: 'notes', operation: 'insert', values }), {
				name: DataApiErrors.InvalidQuery,
			});
		}
	});

	it('refuses empty or non-object values', () => {
		for (const values of [{}, null, 'x', 42]) {
			assert.throws(() => validateIn({ table: 'notes', operation: 'insert', values }), {
				name: DataApiErrors.InvalidQuery,
			});
		}
	});

	it('refuses values on a read', () => {
		assert.throws(() => validateIn({ table: 'notes', operation: 'select', values: { text: 'x' } }), {
			name: DataApiErrors.InvalidQuery,
		});
	});

	it('bounds the size of an in() list', () => {
		const tooMany = Array.from({ length: 101 }, (_, i) => i);
		assert.throws(
			() => validateIn({ table: 'notes', operation: 'select', filters: [{ column: 'id', operator: 'in', value: tooMany }] }),
			{ name: DataApiErrors.InvalidQuery },
		);
	});

	it('refuses an empty in() list', () => {
		assert.throws(
			() => validateIn({ table: 'notes', operation: 'select', filters: [{ column: 'id', operator: 'in', value: [] }] }),
			{ name: DataApiErrors.InvalidQuery },
		);
	});

	it('refuses a non-object request', () => {
		for (const raw of [null, 'select * from notes', 42, []]) {
			assert.throws(() => validateIn(raw), { name: DataApiErrors.InvalidQuery });
		}
	});
});

describe('data api execution', () => {
	let dir: string;
	let engine: PGliteEngine;
	let db: RLSEnabledDatabase;
	let currentUser: DataApiUser | null;

	const makeApi = (tables: readonly string[] = ['notes']) =>
		createDataApi({ db, schema, tables, auth: async () => currentUser });

	beforeEach(async () => {
		dir = mkdtempSync(join(tmpdir(), 'data-api-test-'));
		engine = new PGliteEngine(dir);
		db = new RLSEnabledDatabase(engine);

		// withRLS issues SET LOCAL ROLE, so the role has to exist in PGlite.
		await engine.execute('CREATE ROLE authenticated');
		await engine.execute(`CREATE TABLE notes (
			id SERIAL PRIMARY KEY,
			owner TEXT NOT NULL DEFAULT current_setting('request.jwt.claims', true)::json->>'sub',
			text TEXT NOT NULL,
			done BOOLEAN NOT NULL DEFAULT FALSE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`);
		await engine.execute('GRANT SELECT, INSERT, UPDATE, DELETE ON notes TO authenticated');
		await engine.execute('GRANT USAGE, SELECT ON SEQUENCE notes_id_seq TO authenticated');
		await engine.execute('ALTER TABLE notes ENABLE ROW LEVEL SECURITY');
		// Supabase-shaped policy: a row belongs to the JWT subject.
		await engine.execute(`CREATE POLICY own_notes ON notes FOR ALL TO authenticated
			USING (owner = current_setting('request.jwt.claims', true)::json->>'sub')
			WITH CHECK (owner = current_setting('request.jwt.claims', true)::json->>'sub')`);

		currentUser = { userId: 'alice', role: 'authenticated', claims: { sub: 'alice' } };
	});

	afterEach(async () => {
		await engine.destroy();
		rmSync(dir, { recursive: true, force: true });
	});

	it('rejects an unauthenticated caller', async () => {
		currentUser = null;
		await assert.rejects(() => makeApi().execute({ table: 'notes', operation: 'select' }), {
			name: DataApiErrors.NotAuthenticated,
		});
	});

	it('authenticates before validating, so probing reveals nothing', async () => {
		currentUser = null;
		// A malformed query from an anonymous caller must still be an auth failure.
		await assert.rejects(() => makeApi().execute({ table: 'secrets', operation: 'select' }), {
			name: DataApiErrors.NotAuthenticated,
		});
	});

	it('round-trips an insert and a select', async () => {
		const api = makeApi();
		await api.execute({ table: 'notes', operation: 'insert', values: { text: 'hello' } });

		const rows = (await api.execute({
			table: 'notes',
			operation: 'select',
			columns: ['text', 'owner'],
		})) as Array<{ text: string; owner: string }>;

		assert.deepEqual(rows, [{ text: 'hello', owner: 'alice' }]);
	});

	it('isolates rows between users through RLS', async () => {
		const api = makeApi();
		await api.execute({ table: 'notes', operation: 'insert', values: { text: "alice's note" } });

		currentUser = { userId: 'bob', role: 'authenticated', claims: { sub: 'bob' } };
		await api.execute({ table: 'notes', operation: 'insert', values: { text: "bob's note" } });

		// Bob sees only his own row — enforced by the policy, not by application code.
		const bobRows = (await api.execute({ table: 'notes', operation: 'select', columns: ['text'] })) as Array<{
			text: string;
		}>;
		assert.deepEqual(bobRows, [{ text: "bob's note" }]);

		currentUser = { userId: 'alice', role: 'authenticated', claims: { sub: 'alice' } };
		const aliceRows = (await api.execute({ table: 'notes', operation: 'select', columns: ['text'] })) as Array<{
			text: string;
		}>;
		assert.deepEqual(aliceRows, [{ text: "alice's note" }]);
	});

	it("cannot delete another user's row even when naming its id", async () => {
		const api = makeApi();
		const [alice] = (await api.execute({
			table: 'notes',
			operation: 'insert',
			values: { text: 'private' },
		})) as Array<{ id: number }>;

		currentUser = { userId: 'bob', role: 'authenticated', claims: { sub: 'bob' } };
		const deleted = await api.execute({
			table: 'notes',
			operation: 'delete',
			filters: [{ column: 'id', operator: 'eq', value: alice.id }],
		});
		assert.deepEqual(deleted, [], 'the policy should have matched no rows');

		currentUser = { userId: 'alice', role: 'authenticated', claims: { sub: 'alice' } };
		assert.equal(
			((await api.execute({ table: 'notes', operation: 'count' })) as Array<{ count: number }>)[0].count,
			1,
			"alice's row must survive",
		);
	});

	it('counts only rows the caller can see', async () => {
		const api = makeApi();
		await api.execute({ table: 'notes', operation: 'insert', values: { text: 'a' } });

		currentUser = { userId: 'bob', role: 'authenticated', claims: { sub: 'bob' } };
		const counted = (await api.execute({ table: 'notes', operation: 'count' })) as Array<{ count: number }>;
		assert.equal(counted[0].count, 0);
	});

	it('stores an injection attempt as data', async () => {
		const api = makeApi();
		const evil = "'); DROP TABLE notes; --";
		await api.execute({ table: 'notes', operation: 'insert', values: { text: evil } });

		const rows = (await api.execute({ table: 'notes', operation: 'select', columns: ['text'] })) as Array<{
			text: string;
		}>;
		assert.deepEqual(rows, [{ text: evil }]);
	});

	it('refuses to construct with a table missing from the schema', () => {
		// A typo should fail at wiring time, not look like a client error later.
		assert.throws(() => makeApi(['nope']), /not in the schema/);
	});
});

describe('browser client serialization', () => {
	/** Capture what the client would send, without a server. */
	const capture = () => {
		const sent: unknown[] = [];
		const client = createRemoteDataClient<{
			notes: {
				row: { id: number; owner: string; text: string; done: boolean; created_at: Date };
				autoGenerated: 'id' | 'created_at';
				optional: 'done' | 'owner';
			};
		}>(async (query) => {
			sent.push(query);
			return [];
		});
		return { client, sent };
	};

	it('sends a description, never SQL', async () => {
		const { client, sent } = capture();
		await client.from('notes').select('id', 'text').eq('done', false).order('id', 'desc').limit(5);

		assert.deepEqual(sent[0], {
			table: 'notes',
			operation: 'select',
			columns: ['id', 'text'],
			filters: [{ column: 'done', operator: 'eq', value: false }],
			order: [{ column: 'id', direction: 'desc' }],
			limit: 5,
			offset: undefined,
		});
	});

	it('maps eq(column, null) to the is_null operator', async () => {
		const { client, sent } = capture();
		await client.from('notes').select('id').eq('owner', null);

		assert.deepEqual((sent[0] as { filters: unknown[] }).filters, [{ column: 'owner', operator: 'is_null' }]);
	});

	it('produces descriptions the server validator accepts', async () => {
		// Guards against the two halves drifting apart.
		const { client, sent } = capture();
		await client.from('notes').select('id', 'text').gte('id', 1).in('done', [true, false]).limit(5);
		await client.from('notes').update({ text: 'x' }).eq('id', 1);
		await client.from('notes').delete().eq('id', 1);

		const serverSchema: TableSchema = {
			notes: {
				singular: 'note',
				plural: 'notes',
				primaryKey: 'id',
				columns: ['id', 'owner', 'text', 'done', 'created_at'],
				autoGenerated: ['id', 'created_at'],
			},
		};
		for (const query of sent) {
			assert.doesNotThrow(
				() => validateQueryDescription(query, { schema: serverSchema, allowedTables: ['notes'] }),
				`server rejected a client-produced query: ${JSON.stringify(query)}`,
			);
		}
	});
});
