// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * The security boundary for browser-issued queries.
 *
 * Everything arriving here is untrusted: it came from a public HTTP endpoint. The rule
 * is allowlist-only — a table, column, operator or direction is accepted because it
 * appears in the introspected schema or a fixed set, never because it "looks fine".
 *
 * Rejections are deliberately specific about *what kind* of thing was wrong but never
 * echo the schema back, so a prober can't enumerate tables or columns through error
 * messages.
 *
 * @module
 */

import type { TableSchema } from '../crud/types.js';
import { DataApiErrors, blocksError } from './errors.js';
import {
	DATA_API_OPERATIONS,
	DATA_API_OPERATORS,
	type DataApiOperation,
	type DataApiOperator,
	type QueryDescription,
	type ScalarValue,
	type SerializedFilter,
	type SerializedOrder,
} from './types.js';

/** Upper bound on rows a single request may return, unless configured otherwise. */
export const DEFAULT_MAX_LIMIT = 1000;

export interface ValidateOptions {
	schema: TableSchema;
	/** Tables exposed to clients. Opt-in only; anything else is rejected. */
	allowedTables: readonly string[];
	/** Largest `limit` accepted, and the limit applied when none is given. */
	maxLimit?: number;
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
	typeof value === 'object' && value !== null && !Array.isArray(value);

const isScalar = (value: unknown): value is ScalarValue =>
	value === null || typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean';

function reject(message: string): never {
	throw blocksError(DataApiErrors.InvalidQuery, message);
}

/**
 * Validate an untrusted request and return it in canonical form.
 *
 * @throws A `DataApiErrors.InvalidQuery` error for anything not explicitly allowed.
 * @throws A `DataApiErrors.TableNotExposed` error when the table exists but was not
 * opted in, so a misconfiguration is distinguishable from a malformed request.
 */
export function validateQueryDescription(raw: unknown, options: ValidateOptions): QueryDescription {
	const { schema, allowedTables } = options;
	const maxLimit = options.maxLimit ?? DEFAULT_MAX_LIMIT;

	if (!isRecord(raw)) reject('query must be an object');

	// ── Table: allowlist first, so a non-exposed table can't be probed for existence
	const table = raw.table;
	if (typeof table !== 'string') reject('table must be a string');
	if (!allowedTables.includes(table)) {
		throw blocksError(DataApiErrors.TableNotExposed, `table "${table}" is not exposed`);
	}
	const meta = schema[table];
	if (!meta) {
		throw blocksError(DataApiErrors.TableNotExposed, `table "${table}" is not exposed`);
	}
	const columns = new Set(meta.columns);

	// ── Operation
	const operation = raw.operation;
	if (typeof operation !== 'string' || !DATA_API_OPERATIONS.includes(operation as DataApiOperation)) {
		reject('unknown operation');
	}
	const op = operation as DataApiOperation;

	const validated: QueryDescription = { table, operation: op };

	// ── Columns
	if (raw.columns !== undefined) {
		if (!Array.isArray(raw.columns)) reject('columns must be an array');
		for (const column of raw.columns) {
			if (typeof column !== 'string' || !columns.has(column)) reject('unknown column in columns');
		}
		if (raw.columns.length > 0) validated.columns = raw.columns as string[];
	}

	// ── Filters
	if (raw.filters !== undefined) {
		if (!Array.isArray(raw.filters)) reject('filters must be an array');
		validated.filters = raw.filters.map((filter) => validateFilter(filter, columns));
	}

	// ── Order
	if (raw.order !== undefined) {
		if (!Array.isArray(raw.order)) reject('order must be an array');
		validated.order = raw.order.map((term) => validateOrder(term, columns));
	}

	// ── Limit / offset
	// A limit is always applied: without one, a single browser request could pull an
	// entire table.
	validated.limit = validateLimit(raw.limit, maxLimit);
	if (raw.offset !== undefined) {
		if (!Number.isInteger(raw.offset) || (raw.offset as number) < 0) reject('offset must be a non-negative integer');
		validated.offset = raw.offset as number;
	}

	// ── Values, for writes
	if (op === 'insert' || op === 'update') {
		validated.values = validateValues(raw.values, meta.columns, meta.autoGenerated);
	} else if (raw.values !== undefined) {
		reject(`values is not valid for operation "${op}"`);
	}

	// A write with no filter would hit every row. Insert is exempt: it has no filter.
	if ((op === 'update' || op === 'delete') && (validated.filters?.length ?? 0) === 0) {
		reject(`operation "${op}" requires at least one filter`);
	}

	return validated;
}

function validateFilter(raw: unknown, columns: ReadonlySet<string>): SerializedFilter {
	if (!isRecord(raw)) reject('each filter must be an object');

	if (typeof raw.column !== 'string' || !columns.has(raw.column)) reject('unknown column in filters');

	const operator = raw.operator;
	if (typeof operator !== 'string' || !DATA_API_OPERATORS.includes(operator as DataApiOperator)) {
		reject('unknown filter operator');
	}
	const op = operator as DataApiOperator;

	if (op === 'is_null') {
		// The column is the whole condition; a value would be meaningless.
		return { column: raw.column, operator: op };
	}

	if (op === 'in') {
		if (!Array.isArray(raw.value) || raw.value.length === 0) reject('"in" requires a non-empty array');
		// Bound as one parameter per element, so length is a resource concern.
		if (raw.value.length > 100) reject('"in" accepts at most 100 values');
		for (const item of raw.value) {
			if (!isScalar(item)) reject('"in" values must be scalars');
		}
		return { column: raw.column, operator: op, value: raw.value as ScalarValue[] };
	}

	if (op === 'like' || op === 'ilike') {
		if (typeof raw.value !== 'string') reject(`"${op}" requires a string pattern`);
		return { column: raw.column, operator: op, value: raw.value };
	}

	if (!isScalar(raw.value)) reject('filter value must be a scalar');
	return { column: raw.column, operator: op, value: raw.value };
}

function validateOrder(raw: unknown, columns: ReadonlySet<string>): SerializedOrder {
	if (!isRecord(raw)) reject('each order term must be an object');
	if (typeof raw.column !== 'string' || !columns.has(raw.column)) reject('unknown column in order');
	if (raw.direction !== 'asc' && raw.direction !== 'desc') reject('order direction must be "asc" or "desc"');
	return { column: raw.column, direction: raw.direction };
}

function validateLimit(raw: unknown, maxLimit: number): number {
	if (raw === undefined) return maxLimit;
	if (!Number.isInteger(raw) || (raw as number) < 0) reject('limit must be a non-negative integer');
	if ((raw as number) > maxLimit) reject(`limit exceeds the maximum of ${maxLimit}`);
	return raw as number;
}

function validateValues(
	raw: unknown,
	columns: readonly string[],
	autoGenerated: readonly string[],
): Record<string, ScalarValue> {
	if (!isRecord(raw)) reject('values must be an object');

	const known = new Set(columns);
	const generated = new Set(autoGenerated);
	const result: Record<string, ScalarValue> = {};

	for (const [column, value] of Object.entries(raw)) {
		if (!known.has(column)) reject('unknown column in values');
		// Server-managed columns are the database's to set. Accepting one would let a
		// client choose its own id or forge a created_at.
		if (generated.has(column)) reject(`column "${column}" is managed by the database`);
		if (!isScalar(value)) reject('values must be scalars');
		result[column] = value;
	}

	if (Object.keys(result).length === 0) reject('values must not be empty');
	return result;
}
