// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import assert from 'node:assert';
import { describe, test } from 'node:test';
import { buildMigrationPlan, foreignKeysOf, formatMigrationPlan, replaceOutsideLiterals } from './migrations/plan.js';

describe('migration rewriter', () => {
	test('distributed: DDL runs outside the transaction, DML inside', () => {
		const plan = buildMigrationPlan(
			{
				'001.sql':
					"CREATE TABLE t (id TEXT PRIMARY KEY);\nINSERT INTO t VALUES ('a');\nINSERT INTO t VALUES ('b');",
			},
			'distributed',
		);
		const steps = plan.files[0].steps;
		assert.deepStrictEqual(
			steps.map((s) => s.transactional),
			[false, true, true],
		);
	});

	test('distributed: SERIAL becomes an identity column with CACHE 65536', () => {
		const plan = buildMigrationPlan(
			{ '001.sql': "CREATE TABLE t (id SERIAL PRIMARY KEY, note TEXT DEFAULT 'serial');" },
			'distributed',
		);
		const sql = plan.files[0].steps[0].sql;
		assert.match(sql, /id INTEGER GENERATED BY DEFAULT AS IDENTITY \(CACHE 65536\) PRIMARY KEY/);
		assert.match(sql, /DEFAULT 'serial'/, 'literals are untouched');
	});

	test('distributed: CREATE INDEX becomes ASYNC plus a wait on the job', () => {
		const plan = buildMigrationPlan({ '001.sql': 'CREATE INDEX idx ON t (a);' }, 'distributed');
		const [create, wait] = plan.files[0].steps;
		assert.match(create.sql, /CREATE INDEX ASYNC idx ON t \(a\)/);
		assert.strictEqual(wait.kind, 'wait-index-job');
		assert.strictEqual(create.transactional, false);
	});

	test('distributed: ADD CONSTRAINT CHECK gets NOT VALID and a validate step', () => {
		const plan = buildMigrationPlan({ '001.sql': 'ALTER TABLE t ADD CONSTRAINT c CHECK (a > 0);' }, 'distributed');
		const [add, validate] = plan.files[0].steps;
		assert.match(add.sql, /NOT VALID$/);
		assert.strictEqual(validate.kind, 'validate-constraint');
		assert.strictEqual(validate.sql, 'ALTER TABLE t VALIDATE CONSTRAINT c');
	});

	test('distributed: rejects unsupported statements with the file and the doc page', () => {
		assert.throws(
			() => buildMigrationPlan({ '002_rls.sql': 'CREATE POLICY p ON t USING (true);' }, 'distributed'),
			(e: Error) =>
				e.name === 'DsqlMigrationValidationError' &&
				/002_rls\.sql: Row Level Security needs a 'provisioned' cluster/.test(e.message) &&
				/docs\.aws\.amazon\.com\/aurora-dsql/.test(e.message),
		);
		assert.throws(
			() => buildMigrationPlan({ '003.sql': 'ALTER TABLE t ALTER COLUMN a SET NOT NULL;' }, 'distributed'),
			/SET NOT NULL/,
		);
	});

	test('provisioned: the same files run in one transaction with DSQL-only rewrites left out', () => {
		const plan = buildMigrationPlan(
			{
				'001.sql':
					'CREATE TABLE t (id SERIAL PRIMARY KEY);\nCREATE INDEX ASYNC idx ON t (id);\nCREATE POLICY p ON t USING (true);',
			},
			'provisioned',
		);
		const steps = plan.files[0].steps;
		assert.strictEqual(steps.length, 3);
		assert.ok(steps.every((s) => s.transactional));
		assert.match(steps[0].sql, /SERIAL/);
		assert.doesNotMatch(steps[1].sql, /ASYNC/);
	});

	test('lists foreign keys with their referential actions', () => {
		const fks = foreignKeysOf(
			'CREATE TABLE posts (id TEXT, user_id TEXT REFERENCES users(id) ON DELETE CASCADE, org_id TEXT REFERENCES orgs(id))',
		);
		assert.deepStrictEqual(fks, ['REFERENCES users(id) ON DELETE CASCADE', 'REFERENCES orgs(id) (NO ACTION)']);
	});

	test('formatMigrationPlan prints the transaction boundaries and rewrites', () => {
		const plan = buildMigrationPlan(
			{ '001.sql': 'CREATE TABLE t (id TEXT);\nINSERT INTO t VALUES (1);' },
			'distributed',
		);
		const text = formatMigrationPlan(plan, { pending: new Set(['001.sql']) });
		assert.match(text, /001\.sql \[pending\]/);
		assert.match(text, /BEGIN/);
		assert.match(text, /COMMIT/);
		assert.match(text, /record 001\.sql in _migrations/);
	});

	test('replaceOutsideLiterals leaves quoted text alone', () => {
		assert.strictEqual(replaceOutsideLiterals("SELECT 'a b' AS x, a b", /\ba\b/g, 'Z'), "SELECT 'a b' AS x, Z b");
	});
});
