// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Layer 1 of the immutability guard (decision Q5): a **committed baseline
 * file** per block, diffed at synth.
 *
 * Where it lives: `<app>/aws-blocks/baselines/<stack>/<fullId>.auth-pool.json`
 * — next to the backend handler file the `BlocksStack` was created with
 * (`backendHandlerPath`, an absolute path in every template), so it lands in
 * the app's own source tree and resolves to the same file whatever directory
 * synth runs from. Keyed by the stack name and the block's `fullId`.
 *
 * What it records: whether the block owns a user pool and, if so, the four
 * service-immutable properties (`immutability.ts`).
 *
 * - No baseline yet → write one, ask for it to be committed, pass.
 * - A permitted change (anything outside the four, an added custom attribute,
 *   a pool being added) → pass and rewrite the baseline.
 * - A change to one of the four, or the pool going away when the baseline
 *   says it exists → fail synth with the property, old → new, the reason and
 *   the remedy. The baseline is left untouched.
 * - `BLOCKS_AUTH_REBASELINE=<fullId>[,<fullId>…]` → deliberately accept the
 *   current configuration: rewrite the baseline and pass.
 *
 * A baseline whose block is gone (renamed id, or removed) is not checked here
 * — no block reads it. While it records an owned pool it carries a
 * `removalGuard`, and `@aws-blocks/core`'s stack-level check (on every
 * `BlocksStack` / `BlocksBackend`) fails synth for it; that check deletes it
 * on `BLOCKS_AUTH_REBASELINE=<that fullId>` (task D4b).
 *
 * Node `fs` only — runs inside the app's synth process.
 *
 * @internal
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import type { BaselineRemovalGuard } from '@aws-blocks/core/cdk';
import { diffImmutables, type PoolImmutables, parseSnapshot, REMEDY, type Violation } from './immutability.js';

/** The escape hatch: a comma-separated list of block `fullId`s to re-baseline on this synth. */
export const REBASELINE_ENV = 'BLOCKS_AUTH_REBASELINE';

const BASELINE_VERSION = 1;

/** What the current synth provisions for one block. */
export interface PoolState {
	/** The block creates (owns) an `AWS::Cognito::UserPool`. `false` for a pool-less (Q6) or wrapped (`userPool`) config. */
	ownsPool: boolean;
	/** The four properties; `null` exactly when `ownsPool` is `false`. */
	pool: PoolImmutables | null;
}

/** The on-disk baseline. */
export interface PoolBaseline extends PoolState {
	$comment: string;
	version: typeof BASELINE_VERSION;
	stack: string;
	fullId: string;
	/**
	 * Present exactly when `ownsPool` is `true`. Read by `@aws-blocks/core`'s
	 * stack-level check, which runs even when no `Auth` block is left: a
	 * baseline carrying it that no block claims means the block was renamed or
	 * removed, and CloudFormation would delete its pool.
	 */
	removalGuard?: BaselineRemovalGuard;
}

/** The `DESIGN.md` section an orphaned baseline points at. */
export const RENAME_RUNBOOK = '"Renaming or removing an Auth block" in the @aws-blocks/bb-auth DESIGN.md';

/** The removal guard written into the baseline of a block that owns its pool (`userPoolName` is the `fullId`). */
export function poolRemovalGuard(fullId: string): BaselineRemovalGuard {
	return {
		deletes: `the Cognito user pool '${fullId}' and every user in it`,
		rebaselineEnv: REBASELINE_ENV,
		runbook: RENAME_RUNBOOK,
	};
}

export type BaselineOutcome =
	| { status: 'created' | 'updated' | 'rebaselined' | 'unchanged' | 'deferred'; file: string }
	| { status: 'rejected'; file: string; violations: Violation[]; message: string };

/** `<appDir>/baselines/<stack>/<fullId>.auth-pool.json`. */
export function baselinePath(appDir: string, stack: string, fullId: string): string {
	return join(appDir, 'baselines', stack, `${fullId}.auth-pool.json`);
}

/** Whether `BLOCKS_AUTH_REBASELINE` names this block. */
export function rebaselineRequested(env: Record<string, string | undefined>, fullId: string): boolean {
	return (env[REBASELINE_ENV] ?? '')
		.split(',')
		.map((s) => s.trim())
		.includes(fullId);
}

function serialize(stack: string, fullId: string, state: PoolState): string {
	const baseline: PoolBaseline = {
		$comment:
			'Generated by @aws-blocks/bb-auth at synth. Commit this file. It records the user-pool properties Cognito ' +
			`cannot change after creation; a synth that changes one fails. Do not edit by hand — re-baseline with ${REBASELINE_ENV}=${fullId}.`,
		version: BASELINE_VERSION,
		stack,
		fullId,
		ownsPool: state.ownsPool,
		pool: state.pool,
		...(state.ownsPool ? { removalGuard: poolRemovalGuard(fullId) } : {}),
	};
	return `${JSON.stringify(baseline, null, '\t')}\n`;
}

function write(file: string, content: string): void {
	mkdirSync(dirname(file), { recursive: true });
	writeFileSync(file, content);
}

function parseBaseline(raw: string, fullId: string): PoolState | undefined {
	let value: unknown;
	try {
		value = JSON.parse(raw);
	} catch {
		return undefined;
	}
	if (typeof value !== 'object' || value === null) return undefined;
	const record = value as Record<string, unknown>;
	if (record.version !== BASELINE_VERSION || record.fullId !== fullId || typeof record.ownsPool !== 'boolean') {
		return undefined;
	}
	if (!record.ownsPool) return { ownsPool: false, pool: null };
	const pool = parseSnapshot(record.pool);
	return pool ? { ownsPool: true, pool } : undefined;
}

/** `file` relative to the working directory when it is inside it, else absolute. */
function display(file: string): string {
	const rel = relative(process.cwd(), file);
	return rel && !rel.startsWith('..') ? rel : file;
}

function rejection(fullId: string, file: string, violations: Violation[]): string {
	const removal = violations.some((v) => v.property === 'poolRemoved');
	return [
		`Auth '${fullId}': this change cannot be deployed to the existing user pool.`,
		...violations.flatMap((v) => [`  • ${v.change}`, `    ${v.why}`]),
		'',
		removal
			? 'Remedy: keep a pool-backed sign-in method (email + password, a social or SAML provider, or an OIDC provider with ' +
				"`federateVia: 'cognito'`), and keep owning the pool rather than wrapping one via `userPool`."
			: `Remedy: ${REMEDY}`,
		`Baseline: ${display(file)}.`,
		removal
			? `If removing the pool is deliberate, re-baseline: ${REBASELINE_ENV}=${fullId} <your synth/deploy command>, then commit the file.`
			: `If the baseline records a change that was never deployed, re-baseline: ${REBASELINE_ENV}=${fullId} <your synth/deploy ` +
				'command>, then commit the file. (Re-baselining does not make Cognito accept the change; the deploy-time guard still refuses it.)',
	].join('\n');
}

/**
 * Compare the current synth against the baseline at `file`, and write the
 * baseline when the outcome allows it. Never throws on a missing file; the
 * caller fails synth on `status: 'rejected'`.
 */
export function checkBaseline(input: {
	file: string;
	stack: string;
	fullId: string;
	current: PoolState;
	rebaseline: boolean;
	/**
	 * `false` holds back writing a baseline that does not exist yet (status
	 * `deferred`): the stack's synth fails on an orphaned baseline, and after a
	 * rename this new file would be the renamed block's (task D4b).
	 * @default true
	 */
	mayCreate?: boolean;
}): BaselineOutcome {
	const { file, stack, fullId, current } = input;
	const content = serialize(stack, fullId, current);
	if (input.rebaseline) {
		write(file, content);
		return { status: 'rebaselined', file };
	}
	if (!existsSync(file)) {
		if (input.mayCreate === false) return { status: 'deferred', file };
		write(file, content);
		return { status: 'created', file };
	}
	const raw = readFileSync(file, 'utf8');
	const baseline = parseBaseline(raw, fullId);
	if (!baseline) {
		const violations: Violation[] = [];
		return {
			status: 'rejected',
			file,
			violations,
			message: [
				`Auth '${fullId}': the baseline ${display(file)} is unreadable or belongs to another block, so the`,
				'user-pool immutability check cannot run. Restore it from version control, or re-baseline deliberately:',
				`${REBASELINE_ENV}=${fullId} <your synth/deploy command>, then commit the file.`,
			].join('\n'),
		};
	}

	const violations: Violation[] = [];
	if (baseline.ownsPool && !current.ownsPool) {
		violations.push({
			property: 'poolRemoved',
			change: 'the user pool would be removed from the stack (no pool-backed sign-in method is left, or `userPool` now wraps another pool)',
			why:
				'CloudFormation deletes a resource that leaves the template. Under a destroy removal policy that deletes the pool and every ' +
				"user in it; under 'retain' the pool is orphaned, and re-adding a pool-backed method later creates a new, empty pool.",
		});
	} else if (baseline.pool && current.pool) {
		violations.push(...diffImmutables(baseline.pool, current.pool));
	}
	if (violations.length > 0) {
		return { status: 'rejected', file, violations, message: rejection(fullId, file, violations) };
	}
	if (raw === content) return { status: 'unchanged', file };
	write(file, content);
	return { status: 'updated', file };
}
