included:
  - Sources
  - Tests
  - Demo/swift-demo

excluded:
  - .build
  - Demo/swift-demo/Generated

analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - empty_count

closing_brace: error
colon:
  severity: error
comma: error
cyclomatic_complexity:
  warning: 30
  error: 35
empty_count:
  severity: warning
empty_enum_arguments: error
file_length:
  warning: 1500
  error: 2000
function_body_length:
  warning: 250
  error: 300
function_parameter_count:
  warning: 8
  error: 10
identifier_name:
  excluded:
    - id
    - of
    - or
line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  warning: 160
  error: 160
opening_brace:
  severity: error
return_arrow_whitespace: error
statement_position:
  severity: error
trailing_semicolon: error
type_body_length:
  warning: 1250
  error: 1500
non_optional_string_data_conversion:
  severity: error
